"""Attaleiates, Historia, Bonn pp. 168.3-180.3: the coup, the civil war and
the blinding (autumn 1071 - summer 1072). Same edition, scans and conventions
as tools/attaleiates_text.py; every page read against the image
(leaf n = page + 20). The two lacunae Bekker prints on p. 173 are kept as
printed (". . ."). English: the site's working translation (CC0)."""

COUP = [
    {"pg": "168.3–168.13", "titel": "Paul the proedros rides for the City",
     "orig": "Ἤλαυνε μὲν οὖν ὁ βασιλεὺς ἐξ ἑῴας πρὸς τὴν ἑσπέραν μέχρι Κολωνείας αὐτῆς· ἐπὰν δὲ γένοιτο ἐντὸς τοῦ Μελισσοπετρίου (κάστρον δὲ τοῦτο ἐπί τινος λόφου κείμενον), ἤρξαντο τούτῳ προσομιλεῖν τὰ δεινά. ὁ γὰρ σύμβουλος αὐτῷ καὶ πρῶτα τῇ στρατηγίᾳ Παῦλος πρόεδρος, ὃν ἀπὸ τοῦ κατεπανικίου τῆς Ἐδέσσης μεταπεμψάμενος ὁ βασιλεὺς ἐν τῷ πρὸς Πέρσας ἐλαύνειν εὗρεν ἐν Θεοδοσιουπόλει σχεδιάζοντα τὴν ταύτης ἀρχὴν διὰ τὸ τὸν δοῦκα προαλωθῆναι μετὰ τοῦ βασιλέως, καὶ πάντα ἐδόκει αὐτῷ συναιρόμενον, νύκτωρ διαδρὰς τὴν βασιλίδα κατέλαβε, μαθὼν τὰ γεγενημένα κατ᾽ αὐτὴν καὶ τὴν τῆς Αὐγούστης προαίρεσιν.",
     "en": "So the emperor rode from east to west as far as Koloneia itself; and when he was within Melissopetrion (a fort lying on a hill), misfortunes began to keep him company. His counsellor and first man in the command, Paul the proedros, whom the emperor had summoned from the katepanate of Edessa and, on his march against the Persians, had found at Theodosiopolis improvising its government because its doux had been taken before, with the emperor, and who seemed to share in everything with him, slipped away by night and reached the capital, having learned what had been done there and what the Augusta intended.",
     "note": "Melissopetrion lay between Koloneia and the Black Sea coast. The doux of Theodosiopolis 'taken before' is Basilakes (Att. Battle [3])."},
    {"pg": "168.13–169.9", "titel": "The empress, the Caesar, and a convent on the Bosporus",
     "orig": "αὕτη γὰρ ἀπογνοῦσα τὴν τοῦ βασιλέως ἀπόλυσιν μετεπέμψατο μὲν καὶ τὸν τοῦ πρώτου ἀνδρὸς καὶ βασιλέως ὁμαίμονα Ἰωάννην τὸν Καίσαρα μετὰ δύο αὐτοῦ υἱῶν, ὧν ὁ εἷς ὁ Ἀνδρόνικος νέηλυς ἦν ἐκ τῆς στρατιᾶς καταλαβὼν ἐν φυγῇ, διεπέμψατο δὲ καὶ δόγματα πρὸς πάσας τὰς ἐπαρχίας, μὴ ὅλως ἀπαντῆσαι τῷ Διογένῃ διαταττόμενα καὶ τὴν βασιλικὴν τούτῳ προσκύνησιν προσενεγκεῖν καὶ τιμήν. ἀλλὰ τοῦ Καίσαρος εἰσιόντος μετὰ τῶν δύο υἱέων καὶ τῇ βασιλίδι προσμίξαντος ἐν τῷ παλατίῳ, μεταστρέφεται κατ᾽ αὐτῆς ἡ βουλὴ τῆς τοῦ ἀνδρὸς ἀποκηρύξεως καὶ διώξεως. διὸ καὶ τὸν μὲν πρῶτον υἱὸν αὐτῆς, ὃν ἐκ τῆς τοῦ Δούκα συναφείας ἀπέτεκεν, αὐτοκράτορα καὶ δεσπότην φημίζουσιν, ἐν τῷ τοῦ χρυσοτρικλίνου βασιλείῳ θρόνῳ καθιδρύσαντες αὐτόν, καὶ τὴν ἀρχὴν ἐγχειρίζουσι μόναρχον· τήν τε δέσποιναν καὶ μητέρα τούτου καθαιροῦσι μετὰ σφοδρᾶς τῆς ἐπιφορᾶς, εἶτα καὶ πλοίῳ παραδόντες ὑπερόριον τίθενται κατὰ τὸν ἑῷον πορθμόν, ὃν Στενὸν οἱ πολῖται κατονομάζουσιν ἐκ τῆς θέσεως, ἐγκαταστήσαντες ταύτην τῷ παρ᾽ αὐτῆς συστάντι φροντιστηρίῳ καὶ λεγομένῳ Πιπερούδη, μελαμφοροῦσαν ἐπαποδείξαντες καὶ κεκαρμένην τὰς τρίχας, καὶ τῷ τάγματι τῶν μοναζουσῶν καταζεύξαντες.",
     "en": "For she, despairing of the emperor's release, had summoned the brother of her first husband and emperor, the Caesar John, with his two sons, one of whom, Andronikos, had lately arrived from the army, reaching the City in flight; and she had sent decrees to all the provinces ordering them not to receive Diogenes at all, nor to offer him the imperial prostration and honour. But when the Caesar came in with his two sons and joined the empress in the palace, the plan of disowning and hunting down her husband was turned against herself. They proclaimed her eldest son, whom she had borne from her union with Doukas, autokrator and master, set him on the imperial throne of the Chrysotriklinos, and handed him the government as sole ruler; the lady, his mother, they deposed with violent haste, put her on a ship and sent her out of the City to the eastern strait that the citizens call the Stenon from its position, and established her in the convent she had founded, called Piperoude, having her put on black and cut her hair, and yoking her to the order of nuns.",
     "note": "In Attaleiates it is the empress herself who first orders the provinces not to receive Romanos; the Caesar then turns the plan against her. Andronikos 'arriving in flight' from the army is the rearguard commander of Att. Battle [12]. The Stenon is the Bosporus. Matthew of Edessa has a simpler story: 'Michael, son of Doukas, had seized the crown' (Matt. Battle [6])."},
    {"pg": "169.10–170.4", "titel": "Dokeia; Constantine Doukas sent out",
     "orig": "Ὁ δ᾽ οὖν Διογένης μέχρι τοῦ θέματος τῶν Ἀρμενιακῶν προϊών, ἐπεὶ τὰ κατ᾽ αὐτὸν ἐπληροφορήθη, καὶ ὡς τοῖς πολίταις καὶ τοῖς ἀνακτόροις ἐπικεκήρυκται, φρούριόν τι κατασχὼν Δόκειαν κατονομαζόμενον ἐκεῖσε κατεστρατοπεδεύσατο. ὁ δὲ Καῖσαρ καὶ ὁ τὰ σκῆπτρα νέον ἐγχειρισθεὶς τούτου ἀνεψιός, μετὰ τὸ πάντα τὰ κατὰ τὴν βασιλεύουσαν διαθεῖναι κατὰ τὸ βεβουλευμένον αὐτοῖς, καὶ τοὺς μὲν τῆς συγκλήτου βουλῆς οἰκειώσασθαι καὶ τιμᾶν αὐτοὺς προκατάρξασθαι, πρὸς δὲ τοὺς τῆς ἀγορᾶς τὰ συνήθη δημηγορῆσαι καὶ ὡς τὴν πατρῴαν βασιλείαν ψήφῳ θεοῦ εἰς ἑαυτὸν ἀνεκτήσατο, καὶ ὑποσχέσεσι φιλανθρώποις εὐέλπιδας τούτους ποιήσασθαι, στρατιὰν πέμψαι κατὰ τοῦ Διογένους ἐσκέψαντο. καὶ στρατηγὸν αὐτοκράτορα προχειρισάμενοι τῶν τοῦ Καίσαρος υἱῶν ἕνα, Κωνσταντῖνον ὀνόματι, τὸ ἀξίωμα πρωτοπρόεδρον, τοὺς παρατυχόντας τῶν στρατιωτῶν αὐτῷ ἐγχειρίζουσι, καὶ ταχέως τῆς βασιλευούσης ἐκπέμπουσιν· ὃς καὶ ἄλλους τῶν ἐπαρχιῶν συλλεξάμενος, οὓς δὲ καὶ διὰ γραμμάτων βασιλικῶν ἑαυτῷ συστησάμενος, ἁδράν τινα δύναμιν ἔδοξε συναγηοχέναι, καὶ πλησίον τοῦ κρησφυγέτου τῆς Δοκείας τὸν χάρακα ἔθετο.",
     "en": "Diogenes, advancing as far as the theme of the Armeniakoi, learned how things stood with him, and that he had been proclaimed an outlaw to the citizens and the palace; he seized a fort called Dokeia and camped there. The Caesar and his nephew, lately handed the sceptre, having arranged everything in the capital as they had planned (winning over the members of the senate and being first to honour them, making the customary speeches to the people of the market, how he had recovered his father's throne by the vote of God, and filling them with good hopes by kindly promises), resolved to send an army against Diogenes. They appointed one of the Caesar's sons, Constantine by name, a protoproedros by rank, commander-in-chief, gave him the soldiers who happened to be at hand and sent him quickly out of the City. He gathered others from the provinces and won still others over by imperial letters, and seemed to have collected a considerable force; and he pitched his palisade near the refuge of Dokeia.",
     "note": "Dokeia is Tokat. Ibn al-Athīr has Romanos learn the news at 'the fortress of Duqiya' and send Michael an offer to keep the treaty (IA Battle [10])."},
]

CIVIL = [
    {"pg": "170.5–171.19", "titel": "Alyates blinded with tent pegs",
     "orig": "προσερρύησαν δὲ τῷ Διογένῃ τῶν Φράγγων οἱ πλείους, κἀκ τούτου ἔχειν τὸ ἰσχυρὸν προσεδόκα. ἔκτοτε οὖν παροδικαὶ μάχαι τοῖς μέρεσι διερρήγνυντο· οὐδεμία δ᾽ αὐτοτελὴς τὴν ἔκβασιν ἔκρινε, συναπτομένων ἀλλήλοις κατ᾽ ἄνδρας καὶ αὖθις ἀπαλλαττομένων τῶν ἀντιθέτων στρατιωτῶν. ὡς δὲ πολλοὺς τῶν Καππαδοκῶν ὁ βασιλεὺς κηρύγμασί τε καὶ γράμμασι μετεπέμψατο, ὧν ἦρχε Θεόδωρος πρόεδρος ὁ Ἀλυάτης, ἀνὴρ γένους ἐπιφανοῦς τὰ πολεμικὰ καὶ θεαθῆναι θαυμασιώτατος, μεγέθει καὶ ὄγκῳ τῶν πολλῶν διαφέρων καὶ ἱκανῶς ἐν πολλοῖς στρατευσάμενος, ἔδοξεν ὁ Διογένης πολὺ τῶν ἐναντίων προέχειν, καὶ ταχὺ τοῦ τῆς Δοκείας ἄρας φρουρίου πρὸς τὴν τῶν Καππαδοκῶν ἤλαυνεν, ἐξ ἧς περ αὐτὸς τὴν γένεσιν ἔσχηκεν. ἀλλ᾽ οἱ τῆς μοίρας τοῦ τὴν βασιλείαν ἐν Κωνσταντινουπόλει κατέχοντος, παρὰ δόξαν προσθήκην δεξάμενοι κατὰ τὴν νύκτα ἐκείνην, οὐ πολὺ τὸ ἔλαττον ἀπενέγκασθαι διεγνώκεσαν. κατέλαβε γὰρ αὐτοὺς μεθ᾽ ἑτέρων ἐκ τῆς βασιλίδος ἀποσταλεὶς σύμμαχος ὁ Φράγγος ἐκεῖνος Κρισπῖνος, ὃν ὁ Διογένης μὲν ἐπ᾽ αἰτίαις ἀποστασίας καθελὼν ἐκ τῆς στρατιᾶς ὑπερόριον εἰς Ἄβυδον ἐποιήσατο, ὁ δ᾽ ἀντιβασιλεύσας ὕστερον Μιχαὴλ ἐκ τῆς ὑπερορίας μεταγαγὼν εὐεργεσίαις καὶ τιμαῖς κατελάμπρυνε καὶ πρὸς τὴν ἑαυτοῦ ἀνέρρωσεν εὔνοιαν. οὗτος οὖν γενναιότατος κατὰ χεῖρα τελῶν, καὶ ἀλκιμώτατος, εἴπερ τις ἀνθρώπων, δοκῶν διὰ τὸ πεῖραν δοῦναι τῆς ἑαυτοῦ δοκιμότητος ἐκ τῶν φθασάντων αὐτοῦ ἀνδραγαθημάτων, πολλὴν ἐνέσταξε προθυμίαν τοῖς στρατιώταις, ἐν ὥρᾳ καταλαβὼν πολεμικῆς ἐπιδόσεως. διὰ ταῦτά τοι καὶ ἄραντος ἐκ Δοκείας τοῦ Διογένους ἐπεφάνησαν καὶ οἱ τοῦ βασιλέως τὰς σημαίας ὑπερτεταμένας ἐκφέροντες. ἀλλ᾽ ὁ Ἀλυάτης τούτων κατεπαρθείς, πολλοὺς τῶν στρατιωτῶν συναγηοχώς, πόλεμον τούτοις προσέμιξεν. ἐρρωμένως δὲ ἀντιταξαμένων αὐτῶν, καὶ μᾶλλον ἐπιφημισθέντος τοῦ Κρισπίνου παρεῖναι καὶ τοῖς Φράγγοις τῇ πατρίῳ διαλεχθέντος φωνῇ, πρὸς φυγὴν οἱ τοῦ Ἀλυάτου ἀτάκτως ὥρμησαν· ἀφ᾽ ὧν τινὲς μὲν ἀκοντίοις ἀπέθανον, ἁλοὺς δ᾽ αὐτὸς τοὺς ὀφθαλμοὺς ἐξεκόπη, μετὰ σκηνικῶν σιδήρων περιωδύνως τὰς ὁράσεις ἀποβαλών. ὅπερ πολλὴν ἐνῆκε τοῖς στρατιώταις ἀνίαν διὰ τὸ τοῦ ἀνδρὸς ἐπίσημον κατὰ γένος καὶ γενναιότατον.",
     "en": "Most of the Franks flowed over to Diogenes, and from them he expected to have strength. From then on passing fights broke out between the two sides; none decided the outcome by itself, the opposing soldiers engaging man to man and separating again. When the emperor had summoned many of the Cappadocians by proclamations and letters, under the command of Theodore Alyates the proedros, a man of illustrious family in war and most admirable to look at, surpassing most men in size and bulk and experienced in many campaigns, Diogenes seemed to be far ahead of his enemies, and quickly left the fort of Dokeia and marched towards Cappadocia, the land he himself came from. But the party of the man who held the throne in Constantinople received, against expectation, a reinforcement that very night, and resolved to come off not much the worse. For there joined them, sent from the capital with others as an ally, that Frank Crispin, whom Diogenes had removed from the army for rebellion and exiled to Abydos, and whom Michael, who afterwards reigned in his place, brought back from exile, loaded with favours and honours and won to his own goodwill. This man, most valiant with his hands and as brave as any man alive, since he had given proof of his worth by his earlier deeds of prowess, poured great eagerness into the soldiers, arriving at the moment of warlike effort. So when Diogenes set out from Dokeia, the emperor's men appeared too, carrying their standards raised high. Alyates, elated against them, gathered many of the soldiers and gave battle. But they resisted stoutly, and all the more when word went round that Crispin was there and he spoke to the Franks in their own tongue; Alyates' men broke into disorderly flight. Some of them died by javelins; Alyates himself was taken and had his eyes gouged out, losing his sight in agony by means of tent pegs. This caused the soldiers great distress, because of the man's distinguished family and his great valour.",
     "note": "Crispin is the Norman captain whose rebellion the game's card 'The Frankish captain rebels' (1069) draws on: exiled by Romanos, recalled by Michael, and decisive against him. The Franks change sides by language as much as by pay. The first blinding of the civil war is Alyates'; Romanos' own follows (Att. Blind. [4])."},
    {"pg": "171.20–172.17", "titel": "Khatchatour comes over; winter in Cilicia",
     "orig": "Περιώδυνος δ᾽ ὁ Διογένης ἐκ τῆς φήμης γενόμενος, ὅμως τὸ λοιπὸν ἄγων πλῆθος εἰς τὴν Καππαδοκῶν ἐνέβαλε γῆν· καὶ εἴς τι φρούριον ἀνιὼν Τυροποιὸν οὕτως ὀνομαζόμενον, ἐπὶ λόφου κείμενον ὀχυροῦ, ἐκαραδόκει τὸ μέλλον, πανταχόθεν ἐπικαλούμενος στρατιώτας εἰς τὴν ἑαυτοῦ ἀρωγήν. ἐπεὶ δὲ παρὰ τοῦ τὴν Βύζαντος βασιλεύοντος μετεπέμφθη ὁ τῆς μεγάλης Ἀντιοχείας κατεπάνω, Χατατούριος ἐπονομαζόμενος, ἐξ Ἀρμενίων δ᾽ ἕλκων τὸ γένος, καὶ προσετάγη πόλεμον τῷ Διογένῃ ἐπενεγκεῖν, ἀφίκετο μὲν εἰς Τυροποιὸν μετὰ πολλῆς τῆς δυνάμεως ἱππέων τε καὶ πεζῶν, κατοικτισάμενος δὲ τὸν Διογένην τῆς τύχης, καὶ ἅμα χάριτας τούτῳ προσομολογεῖν ἔχων ὡς παρ᾽ ἐκείνου τὴν ἀρχὴν τῆς Ἀντιοχείας λαβών, συνέθετο τούτῳ καὶ τῆς ἐκείνου μοίρας ἐγένετο, καί τινας τῶν στρατιωτῶν, οἷς ἐκ βασιλέως διώριστο συνάρασθαι τούτῳ τῶν κατὰ Διογένους μόθων, τῶν ἵππων ἀποστερήσας καὶ τῆς ἄλλης ἀποσκευῆς γυμνοὺς ἐκεῖθεν ἀπήλασεν. εἶτα μικρόν τι διαλιπὼν σὺν τῷ βασιλεῖ καὶ τοῖς ἀμφ᾽ αὐτὸν στρατιώταις εἰς τὴν τῶν Κιλίκων χώραν διέζευξεν, ὁμοῦ μὲν παραχειμασίαν ἐν αὐτῇ ποιησόμενος (παρήμειπτο γὰρ τὸ φθινόπωρον), ὁμοῦ δὲ δύναμιν ἑτέραν ἐν τῷ ἀσφαλεῖ συλλεξόμενος καὶ τοὺς ἀπὸ τοῦ σουλτάνου πεμφθησομένους μετὰ διορίαν τοιαύτην καταλαβεῖν.",
     "en": "Diogenes was deeply grieved by the news, but he led the rest of his host into Cappadocia; and going up to a fort called Tyropoion, lying on a strong hill, he waited for what would come, calling soldiers from everywhere to his aid. The katepano of great Antioch, called Khatatourios, of Armenian descent, was summoned by the man who reigned in Byzantium and ordered to make war on Diogenes. He came to Tyropoion with a large force of horse and foot; but taking pity on Diogenes' fortune, and at the same time owing him gratitude, since he had received the command of Antioch from him, he came to terms with him and joined his side; and certain soldiers who had been ordered by the emperor to help him in the fighting against Diogenes he stripped of their horses and other equipment and drove away naked. Then, after a short while, he crossed with the emperor and the soldiers around him into Cilicia, both to winter there (for the autumn was past) and to gather another force in safety and to receive those whom the sultan would send under such an agreement.",
     "note": "Khatatourios is the Armenian Khatchatour, Romanos' appointee at Antioch: the Armenian lord the game's card 'Civil war: Cilicia' calls down from the mountains. 'Those whom the sultan would send under such an agreement' are the troops of the treaty: Ibn al-Athīr's terms bound the emperor to send troops to the sultan (IA Battle [9]); here the sultan's help was expected the other way."},
    {"pg": "172.18–173.15", "titel": "The worse counsel",
     "orig": "Ἔλαθον δὲ τὸ ἧττον αἱρετισάμενοι καὶ τὰ χείρω καθ᾽ ἑαυτῶν βουλευσάμενοι. τοῦ γὰρ τροπωσαμένου τὴν πρώτην τὸν Διογένην ἐν τῇ κατὰ τὸν Ἀλυάτην συμβολῇ τῇ βασιλίδι ἐπαναστρέψαντος, διεσκορπίσθη ἅπαν τὸ σὺν αὐτῷ στρατιωτικὸν ὡς τοῦ χειμῶνος ἐγγίσαντος, καὶ ἦν εὐχερὲς τοῖς ἀμφὶ τὸν Διογένην μετὰ τοσούτου πλήθους εἰς τὴν Ῥωμαίων ἐμβαλεῖν, ὅση κατὰ Πισιδίαν καὶ Ἰσαυρίαν καὶ αὐτὴν Λυκαονίαν, εἰς αὐτήν τε τῶν Παφλαγόνων καὶ Ὀνωριάδα, καὶ πάντας τῷ πλήθει βιάσασθαι γενέσθαι ὑφ᾽ ἑαυτόν, εἶτα καὶ εἰς Βιθυνίαν εἰσδῦναι, καὶ πᾶσαν ἄδειαν ἐμφράξαι τοῖς ἐκ τοῦ Βύζαντος στρατιώτας κατ᾽ αὐτοῦ συναγεῖραι καὶ πόλεμον ἐπεγεῖραι τούτῳ ἄξιον λόγου καὶ πράγματος· οἱ γὰρ τῆς ἑσπέρας στρατιῶται τὴν κατ᾽ αὐτοῦ ἐξομόσαντες ἀπιστίαν διὰ τὸ προκατασφαλισθῆναι ὅρκοις μὴ ἄν ποτε συμφρονῆσαι τοῖς κατ᾽ αὐτοῦ γενησομένοις . . . νῦν δὲ μὴ καλῶς βουλευσάμενος κακοῖς ἀπλέτοις καὶ περιωδύνοις περι . . .ρη πράγμασιν. ἐμβαλὼν γὰρ εἰς τὴν τῶν Κιλίκων χώραν, δυσδιοδεύτους αὐλῶνας ἔχουσαν ἐκ τῶν Ταύρου ὀρῶν, ἔμενε κατὰ χώραν ὥσπερ ἑαυτὸν ἐγκαθείρξας ἐπὶ τῷ μένειν ἀπρόϊτον, ἄδειαν δὲ τοῖς ἀντιτεταγμένοις παρέσχεν ἀδεῶς στρατιώτας ἀγείρειν καὶ τὸν πολεμικὸν ποιεῖσθαι κατάλογον.",
     "en": "Without noticing it they chose the weaker course and took counsel for the worse against themselves. For the man who had first routed Diogenes, in the encounter with Alyates, had gone back to the capital, and all his army had scattered as winter came on; and it would have been easy for Diogenes' party, with so large a host, to invade the Roman lands in Pisidia, Isauria and Lykaonia itself, and in Paphlagonia and the Honorias, to force everyone by numbers to come over to him, then to enter Bithynia and cut off from the men in Byzantium every chance of raising soldiers against him and starting a war worth the name; for the soldiers of the West had forsworn disloyalty to him, having been bound beforehand by oaths never to side with those who would move against him . . . But now, having taken bad counsel, he [was caught up] in countless grievous troubles. For he went into Cilicia, whose valleys through the Taurus mountains are hard to pass, and stayed where he was, as if he had shut himself in to stay without going out, and gave his enemies the freedom to raise soldiers without fear and to draw up their muster rolls.",
     "note": "The dots are Bekker's: the manuscript has gaps here, and the sense of the first ('the western troops would have joined him') is supplied only by the context. Attaleiates the strategist: the civil war was lost by a choice of winter quarters, as the battle had been lost by a turned standard."},
    {"pg": "173.15–174.10", "titel": "Andronikos through the Taurus",
     "orig": "ἐκπεμφθεὶς γὰρ ὁ ἕτερος τῶν υἱέων τοῦ Καίσαρος Ἀνδρόνικος πρωτοπρόεδρος, καὶ προβληθεὶς δομέστικος τῆς ἀνατολῆς, ἐν παρασκευῇ πάντας τοὺς στρατιώτας πεποίηκε, σιτηρέσια διανείμας αὐτοῖς καὶ κατὰ μικρὸν ἅπαντας προοικειωσάμενος, συναιρομένου τοῦ Κρισπίνου. καὶ οὕτως μετὰ τὸ συστῆσαι τὴν ὅλην σύνταξιν τῶν δυνάμεων προήει κατὰ τοῦ Διογένους ὡς τῆς Κιλίκων ἐπιβησόμενος, καὶ τὴν συνήθη κλεισοῦραν τὴν τοῦ λεγομένου καταλιπὼν Ποδαντοῦ διὰ τῆς τῶν Ἰσαύρων εἰς ταύτην ἐνέβαλεν, οὐ πάνυ τι ἀπεχούσης τῆς τῶν Ταρσῶν πόλεως. δυσδιεξόδευτοι δ᾽ ὄντες καὶ τραχεῖς καὶ ἀνάντεις καὶ λίαν στενόποροι οἱ διατειχίζοντες τῶν ὀρῶν αὐχένες τὴν Κιλικίαν οὐ μετρίαν ἐποίουν οὐδ᾽ εὔοδον τῷ στρατῷ τὴν εἰσέλευσιν. ὅθεν καὶ εἴ τινες τῶν τοῦ Διογένους τὰς ἀκρωρείας κατεῖχον, καὶ μᾶλλον ἑκηβόλοι καὶ τοῖς ποσὶν ἐπιβαίνοντες, οὐκ ἂν ἠδυνήθη ποτὲ τὸ τοῦ Ἀνδρονίκου στρατόπεδον τὴν πορείαν διὰ τούτων ποιήσασθαι, εἰ μὴ καὶ μᾶλλον δέους ἐπειγομένου τοῖς στρατιώταις πρὸς φυγὴν ὥρμησαν. τούτου δὲ παραμεληθέντος εἰς κίνδυνον περιέστη τῷ Διογένῃ τὰ πράγματα.",
     "en": "For the other son of the Caesar, Andronikos the protoproedros, was sent out and appointed domestikos of the East; he made all the soldiers ready, distributed rations to them and little by little won them all over, with Crispin's help. And so, having put together the whole order of his forces, he advanced against Diogenes to enter Cilicia; leaving the usual pass, the one called Podandos, he went into it through Isauria, not very far from the city of Tarsus. The mountain necks that wall off Cilicia, hard to get through, rough, steep and very narrow, made the way in neither easy nor passable for an army. So if some of Diogenes' men had held the heights, archers above all and men nimble on their feet, the army of Andronikos could never have made its way through them; rather, with fear pressing on them, the soldiers would have turned to flight. But this was neglected, and Diogenes' affairs came into danger.",
     "note": "The same Andronikos who, 'as most people assert', broke the rearguard at Manzikert (Att. Battle [12]) now commands the army that ends Romanos' reign. Attaleiates does not make the connection aloud. Podandos is the usual pass of the Cilician Gates."},
    {"pg": "174.10–175.2", "titel": "Khatchatour taken; Adana; the terms",
     "orig": "μετὰ γὰρ τὸ κατελθεῖν εἰς τὸ πεδίον τὸν σὺν τῷ Ἀνδρονίκῳ στρατὸν ὁ Χατατούριος ἐπελθὼν πόλεμον τούτοις συνέρρηξεν. οὐ διὰ πολλῆς δὲ γενομένου τῆς ὥρας αὐτοῦ ὡς ἂν τῶν Ῥωμαϊκῶν δυνάμεων τῷ τε πλήθει καὶ τῇ ἀρετῇ ὑπερεχουσῶν, πεσὼν ἐκ τοῦ ἵππου ὁ Χατατούριος πεζὸς ἑάλω, καὶ τῷ στρατηγοῦντι παρέστη γυμνὸς καὶ ἐλεεινὸς τῇ παρούσῃ τύχῃ καὶ τῇ ἐλπίδι τῶν μελλόντων κακῶν. τῶν δ᾽ ἄλλων συμφυγόντων εἰς τὸ τῆς Ἀδάνης κάστρον, ἐν ᾧ περ ὁ Διογένης ἐκάθητο, πολιορκία τὴν τοιαύτην πόλιν ἀκριβῶς διεδέξατο· περικαθίσαντες γὰρ αὐτὴν οἱ μετὰ τοῦ Ἀνδρονίκου Ῥωμαῖοι σπάνει τῶν ἀναγκαίων τοὺς ἔνδον οὐκ εἰς μικρὰν τὴν ἀγωνίαν ἐνέβαλον. τέως δ᾽ οὖν περὶ σπονδῶν διαλεχθέντων ἀλλήλοις, συνέδοξεν ἀποθέσθαι μὲν τὴν βασιλείαν τὸν Διογένην, συναποθέσθαι δὲ καὶ τὴν τρίχα, καὶ οὕτω τὸν βίον ἕλκειν ἄχρι βιοτῆς ἁπάσης τοῖς μοναχοῖς συγκαταλεγόμενον.",
     "en": "When the army with Andronikos had come down into the plain, Khatatourios attacked and joined battle with them. The fight did not last long, since the Roman forces were superior in numbers and quality; Khatatourios fell from his horse, was taken on foot, and stood before the commander naked and pitiable, in his present fortune and in his expectation of evils to come. The rest fled together into the fortress of Adana, where Diogenes was staying, and a close siege of the town followed: the Romans with Andronikos surrounded it and threw those inside into no small anguish through want of necessities. At last, after they had talked with each other about terms, it was agreed that Diogenes should lay down the throne, lay down his hair with it, and so drag out his life to its end enrolled among the monks.",
     "note": "Attaleiates calls Andronikos' men 'the Romans': in the civil war the word no longer tells the reader whose side is meant. The bishops who guaranteed the terms appear only later, at the blinding (Att. Blind. [4])."},
]

BLINDING = [
    {"pg": "175.3–175.20", "titel": "Out of Adana in black",
     "orig": "Γέγονε τοῦτο, καὶ μετὰ μικρὸν ἐξῆλθε τοῦ κάστρου μελανειμονῶν καὶ τὰ καθ᾽ ἑαυτὸν ὡς ἔσχεν ἀποκλαιόμενος, ὅτε καὶ πολλοῖς εἰσῄει δριμὺς καὶ ἀκάθεκτος ἐπὶ τοῖς ὁρωμένοις φόβος καὶ ἔλεος, λογιζομένοις τὸ ἄστατον τῶν πραγμάτων καὶ πρὸς ἐναντιότητα περιπετὲς καὶ ὀξύρροπον. ἦσαν γὰρ ἅπαντες οἱ τούτῳ πολλάκις συστρατευσάμενοι καὶ δορυφόρων τάξιν πληρώσαντες, καὶ τὸ κράτος αὐτῷ περιφημίζοντες ὄλβιον, καὶ προσιτοὶ γενέσθαι τούτῳ δι᾽ εὐχῆς ὅτι μεγίστης ποιούμενοι, εἶτα καὶ συνεξελθόντες αὐτῷ ἐκ Συρίας καὶ τῇ Ἀδάνῃ ἐμβαλόντες, βασιλικῶς δουλικῶς προσεδρεύσαντες. ἀναπεμπαζόμενοι τοίνυν τήν τε προτέραν εὐτυχίαν καὶ τὴν παροῦσαν ἀτυχίαν, ὅπως εἰς ἄκρον ἐναντιότητος ἥκασι, κατηφιῶντες ἦσαν καὶ ἀμηχανοῦσιν ἐῴκεσαν. νόστου δ᾽ ἐπιμνησθέντος τοῦ στρατηγοῦ, ἐπανήρχετο μὲν ἡ στρατιὰ τὴν ἐπ᾽ οἴκου ἐλαύνουσα, παρεπέμπετο δὲ καὶ ὁ Διογένης, εὐτελεῖ τῷ ὑποζυγίῳ καὶ μοναχικῷ καταστήματι δι᾽ ἐκείνων τῶν κωμῶν καὶ τῶν χωρῶν πορευόμενος, δι᾽ ὧν τὸ πρόσθεν μετὰ βασιλικῆς τῆς δορυφορίας ἰσόθεος ἐγνωρίζετο.",
     "en": "It was done, and shortly afterwards he came out of the fortress dressed in black, weeping over what had become of him; and many were struck with a sharp and uncontrollable fear and pity at the sight, reckoning the instability of affairs and how they swing sharply round to their opposite. For all of them had often campaigned with him and filled the ranks of his guard, had hailed his power as blessed and prayed above all to have access to him, and then had come out with him from Syria and entered Adana, attending on him as their emperor like servants. Counting over his former good fortune and his present misfortune, and how they had come to the very extreme of reversal, they were downcast and looked like men at a loss. When the commander gave the word to go home, the army set out on its way back, and Diogenes was taken along with it, riding a cheap beast of burden in a monk's habit through those villages and lands through which he had once been known, with his imperial guard, as the equal of a god.",
     "note": "Bekker queries βασιλεύοντι for βασιλικῶς. Matthew of Edessa has Romanos put on the habit himself to save his life (Matt. Battle [6])."},
    {"pg": "175.20–176.6", "titel": "Hemlock, and an order from the emperor",
     "orig": "μέχρι δὲ τοῦ Κοτυαείου τὴν πορείαν ὀδυνηρῶς ποιησάμενος (καὶ γὰρ νοσηλευόμενος ἦν ἀπὸ κοιλιακῆς διαθέσεως, ἥτις ἐκ κωνείου τούτῳ κατασκευασθέντος παρὰ τῶν ἐναντίων ἐπιγενέσθαι ἐλέγετο) κατεσχέθη παρὰ τῶν ἀγόντων αὐτόν, ἕως ἐκ βασιλέως πρόσταξίς τις ἐπιφοιτήσει τὸ ποιητέον περὶ αὐτοῦ ἐπιτάττουσα. ἀλλ᾽ ἧκεν ἡμέραις ὕστερον ἡ πάντων ἀπηνεστέρα καὶ ἀποφημοτέρα κατὰ τοῦ τὰ τοιαῦτα δεδυστυχηκότος ἀπόφασις, διοριζομένη τοὺς ὀφθαλμοὺς τούτου παραυτίκα διορυγῆναι.",
     "en": "He made the journey in pain as far as Kotyaion (for he was sick with a disorder of the bowels, which was said to have come on from hemlock prepared for him by his enemies), and there he was held by those who were bringing him, until some order should come from the emperor prescribing what was to be done with him. But days later there came the harshest and most ill-omened of all sentences against the man who had suffered such misfortunes, ordering his eyes to be dug out at once.",
     "note": "Printed ἀθηνεστέρα, a misprint for ἀπηνεστέρα (Bekker's Latin: crudelissima). Kotyaion is Kütahya. The poison is 'said'; the order is not."},
    {"pg": "176.7–177.16", "titel": "“What do you say, emperor?”",
     "orig": "Τί φῄς, ὦ βασιλεῦ καὶ οἱ σὺν σοὶ τὴν ἀνοσίαν βουλὴν κατασκευασάμενοι. ἀνδρὸς ὀφθαλμοὺς μηδὲν ἀδικήσαντος, ἀλλὰ τὴν ἑαυτοῦ ψυχὴν ὑπὲρ πάσης τῆς Ῥωμαίων εὐετηρίας, καὶ τοῖς πολεμικωτάτοις ἔθνεσιν ἀντιταξαμένου μετὰ καρτεροῦ τοῦ συντάγματος, ἐξὸν ὂν αὐτῷ ἀκινδύνως τοῖς βασιλείοις προσμένειν καὶ στρατιωτικοὺς πόνους καὶ φόβους ἀποτινάσσεσθαι; ἐκείνου οὗ καὶ τὴν ἀρετὴν πολέμιος αἰδεσθεὶς ἠσπάσατό τε γνησίως καὶ λόγων καὶ ἁλῶν ὡς ἀδελφῷ μεταδέδωκε, καὶ σύνθρονον τὸν αἰχμάλωτον ἐποιήσατο, καὶ ὡς ἀγαθὸς ἰατρὸς φάρμακον ἀκεσώδυνον τὰς τοιαύτας παρηγορίας τῷ φλεγμαίνοντι τῆς λύπης ἐπέθηκεν, ὥστε δικαίως τὴν νίκην ὑπ᾽ ἀθλοθέτῃ θεῷ λαβεῖν ὁ σουλτάνος διαγινώσκεται, τοιοῦτος ἀποδειχθεὶς ἄνθρωπος, καὶ τοσοῦτον ὄγκον φρονήσεως καὶ ἀνεξικακίας ἐπιδειξάμενος. σὺ δὲ τί προστάττεις, ὦ βασιλεῦ; ἀποστερηθῆναι καὶ αὐτοῦ τοῦ φωτὸς καὶ τῆς δεδομένης αὐτῷ θεόθεν τῶν ὁρωμένων κατανοήσεως τίνα τοῦτον; τὸν πατρὸς ἐπὶ σοὶ πρᾶξιν εἰληφότα καὶ νόμῳ καὶ πράγματι, τὸν ἀποβεβληκότα τὴν βασιλείαν καὶ σοὶ ταύτην προέμενον, τὸν ἐκ πορφυρίδος ῥακοδυτήσαντα, τὸν εἰς βίον μονήρη μεταλλαξάμενον καὶ τοῖς γηΐνοις πᾶσιν ἀποταξάμενον, τὸν ἀσθενῆ καὶ παρειμένον καὶ ἀκεσωδύνου μᾶλλον θεραπείας καὶ ψυχαγωγίας ἐπιδεόμενον, τὸν ἀπειρηκότα τοῖς ὅλοις, ἀσθενοῦντα καὶ κακουχούμενον, τὸν ὡς κάλαμον συντετριμμένον καὶ ὄμβροις δακρύων ἐκτετηκότα τοὺς ὀφθαλμοὺς καὶ τὸ πρόσωπον. ἀλλ᾽ εἰ καὶ ταῦτα τοιαῦτα καὶ τοσαῦτα πρὸς πειθὼ παρακλήσεως, μᾶλλον δὲ πλείω τούτων, ὅσῳ καὶ τὸ ἀγγελικὸν σχῆμα σιωπηρῶς σοι παρίσταται πρὸς παράκλησιν, ἀλλὰ σὺ πάντως τῷ θυμῷ καὶ τῇ ἐπιθυμίᾳ τοῦ βασιλεύειν ἐπιμανῶς καὶ ἀκορέστως τὸ πλεῖον τῆς ῥοπῆς ἐπιδώσειας, μήτε τὸ σχῆμα αἰδούμενος μήτε τὴν μητρῴαν θηλήν, ἧς οἱ παῖδες ἐκείνου καὶ σοὶ ἀδελφοὶ κοινῶς μετεσχήκατε. ὄψεται δὲ πάντως καὶ σέ ποτε ὄμμα τιτανῶδες καὶ κρόνιον, καὶ τὰς τύχας σοι πρὸς τὴν ὁμοίαν παραστήσει κακότητα.",
     "en": "What do you say, emperor, you and those who framed this unholy counsel with you? The eyes of a man who had done no wrong, but had set his own life against the most warlike nations, with a stout army, for the whole welfare of the Romans, when he could have stayed safely in the palace and shaken off the toils and fears of soldiering? Of a man whose valour even the enemy respected: he embraced him sincerely, shared talk and salt with him as with a brother, made the captive the sharer of his throne, and like a good physician laid such consolations as a soothing drug on the inflamed wound of his grief, so that the sultan is judged to have won the victory justly, by God's award, having shown himself such a man and displayed so great a weight of wisdom and forbearance. And you, emperor, what do you order? That this man be deprived of light itself and of the perception of what is seen, given him by God: who is he? The man who had taken a father's part towards you in law and in fact; who laid down the throne and gave it up to you; who exchanged the purple for rags; who changed to the solitary life and renounced all earthly things; who was weak and broken and needed soothing care and comfort rather; who had given up everything, sick and ill-treated; who was crushed like a reed, and had melted his eyes and face in showers of tears. But even if all these things, so many and so great, pleaded for persuasion, or rather more than these, since the angelic habit silently stood by you to plead, you nevertheless, madly and insatiably, gave the greater weight to anger and the desire to reign, respecting neither the habit nor the mother's breast of which his children and you, his brothers, alike partook. But surely one day a Titanic, Kronian eye will look on you too, and bring your fortunes to a like misery.",
     "note": "The historian's apostrophe to Michael VII, the only place in the work where he addresses a living emperor. The 'angelic habit' is the monk's. Eudokia's sons by Romanos and by Constantine X shared the same mother. Attaleiates wrote after 1078, when Michael had himself been driven from the throne into a monastery: the prophecy is written after the fact."},
    {"pg": "177.17–179.4", "titel": "The blinding",
     "orig": "Ἀλλὰ ταῦτα μὲν ὡς ἐν τῷ τραγῳδίας τρύφει διὰ τὸ πάθος παρεκβατικώτερον εἴρηται. ἐπιφοιτήσαντος δὲ τοῦ παγκακίστου τούτου καὶ ἀνοσίου προστάγματος, δεύτερος πάλιν ἀγὼν ὁ περὶ ψυχῆς καὶ φόβος οἷος καὶ κλόνος ἀπαραμύθητος τὸν ἐν τοσούτοις κατέλαβε δυστυχήμασι. διὸ καὶ λιταῖς τοῖς ποσὶ τῶν ἐκεῖσε ἀρχιερέων ἐκυλινδεῖτο, καὶ τὴν ἐκ τούτων βοήθειαν, ὅση τις ἡ ἰσχύς, μετὰ κατωδύνου καὶ ἀφορήτου τῆς συντριβῆς ἐξεκαλεῖτο θερμῶς. παρῆσαν γὰρ ἐκεῖσε ὅ τε Καλχηδόνος ὁ Ἡρακλείας καὶ ὁ Κολωνείας, τὰς σπονδὰς αὐτῷ συντελέσαντες. ὑπεμίμνησκε δὲ αὐτοὺς καὶ ὅρκων καὶ τῶν ἐκ τοῦ θείου νεμέσεων. οἱ δέ, καί περ βοηθῆσαι τούτῳ βουλόμενοι, ὅμως ἀσθενῶς ἔσχον ἀνδρῶν ἀπηνῶν ἅμα καὶ ὠμηστῶν ἀναρπασάντων αὐτὸν καὶ ὡς ἱερεῖον ἀγόντων ἐπὶ τὸ σφάγιον. καὶ εἰς τὸ κάστρον ἐγκλείσαντες, θαμὰ πρὸς πάντας ἐπιστρεφόμενον καὶ τὴν τῶν ἀρχιερέων κατόπιν παρρησίαν ἰδεῖν διηνεκῶς ἐπευχόμενον, οἰκίσκῳ τινὶ παραπέμπουσι, καί τινα Ἰουδαῖον ἀμαθῆ τὰ τοιαῦτα τὴν τῶν ὀφθαλμῶν αὐτοῦ διαχείρισιν ἐπιτρέπουσι. δήσαντες αὐτὸν ἐκ τεσσάρων, καὶ τῷ στήθει καὶ τῇ κοιλίᾳ πολλοὺς δι᾽ ἀσπίδος ἐπιστηρίξαντες, φέρουσι τὸν Ἰουδαῖον περιωδύνως ἄγαν καὶ ἀπηνῶς σιδήρῳ τοὺς ὀφθαλμοὺς αὐτοῦ ἐκταράττοντα, βρυχωμένου κάτωθεν καὶ ταύρειον μυκωμένου καὶ μηδένα τὸν οἰκτείροντα ἔχοντος. οὐ μὴν ἅπαξ τοῦτο παθὼν ἀφείθη τῆς τιμωρίας, ἀλλὰ τριχῇ τὸν σίδηρον τοῖς τούτου κατέβαψεν ὄμμασιν ὁ τῆς θεοκτόνου τυγχάνων σειρᾶς, ἕως καὶ πληροφορίαν δι᾽ ὅρκου κείμενος ἔθετο πᾶσαν τὴν οἰκονομίαν ἐκχυθῆναι καὶ ἀπορρεῦσαι τῶν ἑαυτοῦ ὀφθαλμῶν. ἐγερθεὶς οὖν αἵματι διαβρόχους ἔχων τοὺς ὀφθαλμούς, θέαμα δ᾽ οἰκτρὸν καὶ ἐλεεινὸν καὶ θρῆνον ἐπιφέρον τοῖς ὁρῶσιν ἀκάθεκτον, ἡμιθνὴς ἔκειτο, προκατειργασμένος μὲν καὶ τῇ νόσῳ, τότε δὲ τοῖς ὅλοις ἀπαγορεύων καὶ τῆς βασιλικῆς ἐκείνης λαμπρότητος καὶ τῆς μέχρις οὐρανοῦ φθανούσης δόξης, μᾶλλον δὲ τῆς ὑπὲρ τῶν Ῥωμαίων ἀνδραγαθίας τοιαῦτα κομισάμενος τὰ ἐπίχειρα.",
     "en": "But this has been said by way of digression, as in the grief of a tragedy, out of feeling. When this most wicked and unholy order had come, a second struggle for his life, and a fear and a shaking beyond consolation, seized the man already in so many misfortunes. He threw himself in supplication at the feet of the bishops who were there, and with painful and unbearable contrition begged hotly for their help, as far as their power went. For present there were the bishops of Chalcedon, of Herakleia and of Koloneia, who had concluded the agreement with him. He reminded them of their oaths and of the retribution that comes from God. They, though they wanted to help him, were powerless, since cruel and savage men had seized him and were leading him like a victim to the slaughter. They shut him in the fortress, while he kept turning to everyone and praying continually to see the bishops come after him to speak for him, and took him to a small room, and handed the work on his eyes to a Jew who had no skill in such things. They bound him at four points, pressed many men down on his chest and belly by means of a shield, and had the Jew dig out his eyes with an iron, in great agony and with great cruelty, while he roared from beneath and bellowed like a bull, with no one to pity him. Nor was he released from the punishment after suffering it once: three times the man of the God-killing race plunged the iron into his eyes, until, lying there, he gave assurance on oath that the whole structure of his eyes had poured out and flowed away. So he got up with his eyes soaked in blood, a pitiful and wretched sight that drew uncontrollable lament from those who saw it, and lay half-dead, worn down already by his sickness, and now giving up on everything: such were the wages he received for that imperial splendour, for glory that reached to heaven, or rather for his valour on behalf of the Romans.",
     "note": "The bishops' guarantee is Attaleiates' and is what the game's card 'Adana' offers. The anti-Jewish designation of the man who did the blinding ('of the God-killing race') is the historian's, and is carried as printed: a Byzantine commonplace that lays the cruelty of Christians on a Jew, as Matthew of Edessa does in another figure (Matt. Battle [6]). Bekker queries a dative, 'handed the work to an unskilled Jew'."},
    {"pg": "179.4–179.22", "titel": "Death on Prote",
     "orig": "προαχθεὶς οὖν ἐν εὐτελεῖ τῷ ὑποζυγίῳ μέχρι τῆς Προποντίδος αὐτῆς, ὥσπερ πτῶμα σεσηπὸς εἵλκετο, τοὺς μὲν ὀφθαλμοὺς κατορωρυγμένους ἔχων, τὴν δὲ κεφαλὴν σὺν τοῖς προσώποις ἐξῳδηκυῖαν, καὶ σκώληκας ἐκεῖθεν δεικνὺς ἀποπίπτοντας. ἡμέρας δ᾽ ὀλίγας διαλιπὼν ἐπωδύνως τὸν βίον, καὶ πρὸ τῆς τελευτῆς ὀδωδώς, ἀπολείπει, τῇ νήσῳ τῇ Πρώτῃ τὸν χοῦν ἀποθέμενος κατὰ τὴν ταύτης ἀκρώρειαν, ἔνθα νέον ἐκεῖνος ἐδείματο φροντιστήριον, κηδευθεὶς μὲν πολυτελῶς παρὰ τῆς πρὶν βασιλίδος καὶ ὁμευνέτιδος Εὐδοκίας, τῆς τοῦ κρατοῦντος μητρὸς (ἐκείνη γὰρ αἰτησαμένη τὸν υἱὸν τὴν νῆσον ταύτην καταλαβεῖν τούτῳ τὰ τῆς ὁσίας φιλοφρόνως ἐτέλεσε), μνήμην δὲ καταλιπὼν τοῖς μετέπειτα τῶν τοῦ Ἰὼβ ἐκείνου δυστυχημάτων ὑπερβαίνουσαν τὴν ἀκρόασιν. τοῦτο δὲ θαυμασιώτατον ἅμα καὶ γενναιότατον τοῖς πᾶσι διήγημα καταλέλοιπεν, ὅτι ἐπὶ τοῖς τηλικούτοις πειρασμοῖς καὶ ἀπαραμίλλοις κακοῖς οὐδὲν βλάσφημον ἢ μικρόψυχον ἀπεφθέγξατο, ἀλλ᾽ εὐχαριστῶν διετέλει καὶ χρόνων προσθήκην ἐπιζητῶν ἐν κακοῖς, ἵνα εὐαρεστήσῃ, φησίν, τῷ ποιήσαντι, τὸν τῆς ἀσκήσεως δρόμον διανύων ἐπιπονώτερον.",
     "en": "Brought on a cheap beast of burden as far as the Propontis itself, he was dragged along like a rotting corpse, his eyes dug out, his head and face swollen, and showing worms falling from them. After a few days he left life in pain, stinking before his death, and laid his dust on the island of Prote, on its height, where he had lately built a monastery. He was buried sumptuously by the former empress and his wife Eudokia, the reigning emperor's mother (she had asked her son to go to this island and performed the rites of burial for him with affection), and he left to those who came after a memory surpassing the hearing of the sufferings of Job himself. And he left everyone this most wonderful and noble story: that in such trials and incomparable misfortunes he uttered nothing blasphemous or mean-spirited, but went on giving thanks and asking for more years in his misfortunes, 'so that', he said, 'I may please my Maker', running the course of asceticism with greater toil.",
     "note": "Bekker's margin dates the death October 1071; the modern accounts put the blinding in the summer of 1072 and the death soon after. Prote (Kınalıada) is one of the Princes' Islands in the Sea of Marmara. The codex reads ὁσσίας for ὁσίας."},
    {"pg": "179.23–180.3", "titel": "No one's trials equal his",
     "orig": "Ἀλλ᾽ ὁ μὲν ἐν τοσούτοις ἀνιαρῶς τὸ ζῆν καταστρέψας, πολλὴν τοῖς πειραζομένοις παρηγορίαν ἐνέσταξεν (ὅσῳ γὰρ ἄν τις καὶ πειρασθείη, οὐκ ἂν τοῖς τούτου κακοῖς παρισωθείη ποτέ)·",
     "en": "So he ended his life in grief amid so much, and poured great consolation into those who are tried; for however much anyone may be tried, he could never be made equal to this man's misfortunes.",
     "note": "The next sentence begins Michael VII's reign. The campaign of 1071 fills twenty pages of the Bonn edition, the civil war and the blinding twelve."},
]

SECTIONS_CIVIL = [
    {"id": "coup", "zk": "Att. Coup", "titel": "The coup in Constantinople",
     "blurb": "Autumn 1071. The emperor's counsellor rides ahead to the capital; the empress, despairing of her husband's release, calls in the Caesar John Doukas and orders the provinces not to receive him, and the Caesar turns the plan against her: Michael VII is proclaimed sole emperor, Eudokia shorn and sent to a convent on the Bosporus, and Constantine Doukas marches on Romanos at Dokeia.",
     "units": COUP},
    {"id": "civil", "zk": "Att. Civil", "titel": "The civil war",
     "blurb": "Winter 1071–72. Most of the Franks come over to Romanos, until Crispin, whom he had exiled, speaks to them in their own tongue; his Cappadocian commander Alyates is blinded with tent pegs; the Armenian Khatchatour of Antioch changes sides for him; Romanos winters in Cilicia instead of marching on the capital, and Andronikos Doukas comes through the Taurus unopposed. Adana is besieged, and Romanos agrees to become a monk.",
     "units": CIVIL},
    {"id": "blinding", "zk": "Att. Blind.", "titel": "The blinding",
     "blurb": "Summer 1072. Out of Adana in black on a mule; sick, it was said, with hemlock; held at Kotyaion until an order comes from the emperor. The historian turns to address Michael VII. The bishops who guaranteed the terms are powerless; the blinding, three times over; the road to the Propontis; death on the island of Prote, and burial by Eudokia.",
     "units": BLINDING},
]
