"""Attaleiates, Historia, Bonn pp. 138.15-148.2: the year 1070 and the
departure of 1071. Same edition, scans and conventions as
tools/attaleiates_text.py; every page read against the image
(leaf n = page + 20). English: the site's working translation (CC0)."""

PRELUDE = [
    {"pg": "138.15–139.2", "titel": "Blachernai burns; Manuel Komnenos in command",
     "orig": "καὶ τὸ ἔτος ἐτελεύτα ἐκεῖνο, ἰνδικτιῶνος ἐνισταμένης η΄ τοῦ ,ϛφοη΄ ἔτους, ὅτε καὶ τὸ μέγιστον ἱερὸν τῶν Βλαχερνῶν ἕως ἐδάφους ἐπυρπολήθη.\nἘπεὶ δὲ τὸ ἔαρ ὑποφαίνεσθαι ἤρξατο, ἐσκέψατο τῇ βασιλίδι παρεῖναι ὁ βασιλεὺς καὶ τὴν ἡγεμονίαν τοῦ στρατοῦ πρὸς τὴν ἑῴαν ἑνὶ τῶν προεχόντων ἐμπιστεῦσαι Ῥωμαίων. προκρίνας οὖν Μανουὴλ πρωτοπρόεδρον τὸν Κομνηνόν, καὶ τῷ τοῦ κουροπαλάτου τιμήσας ἀξιώματι, στρατηγὸν τοῦ πολέμου καὶ ἀρχηγὸν τοῦ στρατεύματος ἀποδείκνυσι. τὸ δ᾽ ἐντεῦθεν τὰ προσάντη καὶ δυσχερῆ τῇ Ῥωμαίων βασιλείᾳ συνήντησεν.",
     "en": "And that year came to an end, as the eighth indiction of the year 6578 began; it was then too that the greatest church of the Blachernai was burned to the ground.\nWhen spring began to show itself, the emperor resolved to stay in the capital and to entrust the command of the army in the East to one of the leading Romans. So he chose Manuel Komnenos the protoproedros, honoured him with the rank of kouropalates, and appointed him general of the war and commander of the army. From then on what met the empire of the Romans was uphill and hard.",
     "note": "The eighth indiction of the year 6578 of the world began in September 1069; Bekker's margin reads 1070. The Blachernai church kept the icon of the Virgin that went on campaign with the emperors: the icon before which the soldier lost his nose in 1071 (Att. March [7]). Manuel Komnenos was the eldest brother of the later emperor Alexios I. In the game, this is the card 'A year at home?'."},
    {"pg": "139.3–139.19", "titel": "A young general's victories, and the emperor's face",
     "orig": "Ἐξιὼν οὖν ὁ προβεβλημένος εἰς τοῦτο, εἰ καὶ νέος τὴν ἡλικίαν ἐτύγχανεν, ἀλλά γε πεπλανημένον οὐδὲν οὐδ᾽ ἀπαγὲς καὶ μειρακιῶδες ἐνεργῶν κατεφαίνετο. πολὺν δὲ λόγον ποιούμενος τῶν εἰκότων τάς τε δυνάμεις συνηθροίκει καὶ τῇ Καισαρέων πασίρρωμος ἐπεφοίτησεν, οὐ μόνον τὰ τοῦ στρατοῦ καθιστῶν, ἀλλὰ καὶ τῆς εὐνομίας προσηκόντως φροντίζων, καὶ τοὺς ἀδικοῦντας τῶν στρατιωτῶν ἐκτίσει καὶ προστίμοις τῆς ἀτασθαλίας καθυποβάλλων. πολέμοις δέ τισιν ἐντυχὼν νικητὴς ἀναπέφηνε, καὶ τὴν περὶ αὐτοῦ εὐδοξίαν ἤδη πλατύνειν καὶ μεγαλύνειν διηγωνίζετο. ἀλλ᾽ ὁ κρατῶν ταυτὶ τὰ προτερήματα πυνθανόμενος εὐθυμεῖν μὲν ἐῴκει, ἐνθυμεῖσθαι δέ τι παρὰ τὴν ὁρωμένην ὄψιν οὐκ εἶχέ τις ἀντειπεῖν. ὅμως δ᾽ οὖν, ἵνα τὴν τῆς Ἱεραπόλεως πολιορκίαν ἀποσοβήσῃ καὶ τὴν πιέζουσαν τοὺς ἔνδον σιτοδείαν παραμυθήσηται, μοῖραν οὐκ ἐλαχίστην τοῦ στρατοπέδου ἀποτεμόμενος ἐκεῖσε κατὰ Συρίαν ἀπελθεῖν διωρίσατο, καὶ τοῦτον τὸν τρόπον τῆς ἐκ τούτων ἰσχύος τὸν στρατηγὸν ἀπεστέρησεν.",
     "en": "So the man appointed to this went out, and though he was young in years, he was seen to do nothing wayward, rash or boyish. Taking great care for what was fitting, he gathered his forces and came to Caesarea in full strength, not only putting the army in order but also caring properly for discipline, and subjecting soldiers who did wrong to restitution and to penalties for their misconduct. Meeting some battles, he came out the victor, and was already striving to spread and enlarge his good name. The ruler, hearing of these successes, seemed to be pleased; but that he had something else in mind besides the face he showed, no one could deny. At any rate, to lift the siege of Hierapolis and relieve the famine pressing on those inside, he cut off no small part of the army and ordered it to go there, into Syria; and in this way he deprived the general of their strength.",
     "note": "Hierapolis (Manbij) was the town Romanos had taken in 1068 (Matt. Romanos [3]). Attaleiates suggests without saying it that the emperor weakened a successful young general out of jealousy: the same suspicion of rivals that runs through 1071."},
    {"pg": "139.20–140.11", "titel": "Defeat near Sebasteia",
     "orig": "εἰς δὲ Σεβάστειαν παραγενομένου τούτου μετὰ τῶν ὑπολελειμμένων δυνάμεων, καὶ περὶ τὸ ἄστυ στρατοπεδεύσαντος, ἐπῆλθέ τις πληθὺς Οὐννικὴ πόλεμον τούτῳ καὶ μάχην ἀναρριπίζουσα. ἐξιόντος δ᾽ αὐτοῦ συνέστη μὲν καρτερὰ διαμάχη, φαντασίαν δὲ φυγῆς δεδωκότων τῶν ἐναντίων, οἷα τὰ τούτων μηχανήματα καὶ συνθήματα, ἐπεὶ διασκεδασθέντες οἱ Ῥωμαῖοι ἐδίωκον, ὑποστροφῆς αἰφνιδίου εὐθὺς γενομένης ἐκείνων παλίντροπος ἡ συμπλοκὴ γέγονε, καὶ πολλοὶ μὲν ἑάλωσαν, πλείους δὲ μαχαίρας ἔργον γεγόνασι, συνεάλω δὲ τοῖς ἄλλοις καὶ αὐτὸς ὁ τοῦ πολέμου τὴν στρατηγίαν ἐπέχων. σὺν τοῖς ἄλλοις δὲ καὶ αὐτῆς τῆς παρεμβολῆς παράστασις καὶ διασκύλευσις γέγονεν. καὶ εἰ μὴ τὸ ἄστυ πλησίον ὂν τοὺς πλείστους διέσωσε, πανστρατιᾷ ἐκινδύνευσεν ἂν ἡ τῶν Ῥωμαίων ἡλικία πᾶσα, ὅση πρὸς τὴν ἐνταῦθα ἐκστρατείαν συνέδραμε.",
     "en": "When he reached Sebasteia with the forces left to him and camped about the town, a Hunnic host came against him, stirring up war and battle. He went out, and a hard fight took place; but the enemy gave the appearance of flight, as their tricks and signals go, and when the Romans scattered in pursuit, they suddenly wheeled round, the fight turned the other way, and many were taken and more fell to the sword; and with the others the commander of the war himself was taken. With the rest, the camp itself was captured and plundered. And had not the town nearby saved most of them, the whole youth of the Romans that had gathered for this campaign would have been in danger to the last man.",
     "note": "'Huns' is Attaleiates' classicising word for the Turks. The feigned flight is the tactic the emperor feared at Manzikert when he turned his standard rather than pursue into the dusk (Att. Battle [12]). The victor was the Turkish commander who then went over to Romanos (Att. 1070 [5]); Matthew of Edessa calls him Guedridj (Matt. Sultan [1])."},
    {"pg": "140.12–141.14", "titel": "Chonai, and an emperor kept at home",
     "orig": "Τῆς φήμης δὲ ταύτης καταλαβούσης τὸν βασιλέα, πολλή τις ἀνία κατέσχε καὶ αὐτὸν καὶ ὅσοι τὰ Ῥωμαίων φρονοῦντες ἐτύγχανον. οὔπω δὲ τὰ τῆς φήμης παρήκμασε, καὶ αὖθις ἑτέρα ἐπῆλθε, τοὺς Τούρκους ἀπαγγέλλουσα τὴν ἐν Χώναις πολιτείαν καὶ αὐτὸν τὸν περιβόητον ἐν θαύμασι καὶ ἀναθήμασι τοῦ ἀρχιστρατήγου ναὸν καταλαβεῖν ἐν μαχαίρᾳ, καὶ φόνου μὲν ἅπαντα τὰ ἐκεῖσε πληρῶσαι καὶ λύθρου, πολλὰς δὲ ὕβρεις τῷ ἱερῷ ἐμπαροινηθῆναι, καὶ τὸ δὴ σχετλιώτερον, μὴ τὰς τοῦ χάσματος σήραγγας, ἐν ᾧπερ οἱ παραρρέοντες ποταμοὶ ἐκεῖσε χωνευόμενοι διὰ τῆς τοῦ ἀρχιστρατήγου παλαιᾶς ἐπιδημίας καὶ θεοσημίας ὡς διὰ πρανοῦς ἄστατον τὸ ῥεῦμα καὶ λίαν εὐδρομοῦν ἔχουσι, τοὺς καταφυγόντας διατηρῆσαι καὶ ὑπαλύξαι τὸν κίνδυνον μελετῆσαι, ἀλλ᾽ ὅπερ οὐ γέγονέ ποτε, πλημυρῆσαι τὸ ὕδωρ καὶ οἷον ἀναρροιβδῆσαι καὶ ἀνερεύξασθαι, καὶ πάντας ἄρδην τοὺς καταπεφευγότας κατακλύσαι καὶ διὰ ξηρὰς ὑποβρυχίους ὑποποιήσασθαι. ταῦτα τοιγαροῦν ἐπιδιηγηθέντα πολλὴν ἐνῆκαν τὴν ἀθυμίαν ἡμῖν ὡς ἐκ θεομηνίας τῶν δεινῶν ἐπισυμβαινόντων, καὶ μὴ μόνον τῶν πολεμίων ἀλλὰ καὶ τῶν στοιχείων ἀντιμαχομένων τοῖς καθ᾽ ἡμᾶς. ἀλλὰ καὶ ὡς ἐδοκίμαζε μὲν καὶ οἷον ἐσφάδαζεν ὁ κρατῶν διαπεραιωθῆναι μετὰ τῶν περιόντων αὐτῷ στρατιωτῶν, καὶ τοῖς κατὰ τὴν ἑῴαν παραβοηθῆσαι κατὰ τὸ δυνατόν· ἀπείργετο δὲ τοῖς τε συμβούλοις, καὶ τῇ ἀγνοίᾳ τοῦ πλήθους τῶν ἐναντίων καὶ τῇ παρακοπῇ τῶν μετὰ τοῦ κουροπαλάτου δυνάμεων. ὅθεν καὶ ἄκων τοῖς βασιλείοις ἐπέμεινεν.",
     "en": "When this news reached the emperor, great grief took hold of him and of all who were loyal to the Romans. The news had not yet faded when another came, reporting that the Turks had taken with the sword the town of Chonai and the very church of the Archangel, famous for its miracles and offerings, had filled everything there with slaughter and gore and committed many outrages against the shrine; and, what was more dreadful, that the caverns of the chasm, where the rivers flowing by are funnelled, by the Archangel's ancient visitation and miracle, so that their stream runs restless and swift as down a slope, did not keep safe those who fled into them or help them to escape the danger; but, as had never happened before, the water flooded, as it were whirled up and belched forth, and drowned all who had fled there to the last man, making them sink under water on dry land. The telling of these things threw us into deep despondency, as if the terrible things were happening by the wrath of God, and not only the enemy but the very elements were fighting against us. Even so the ruler was eager, and all but throbbing, to cross over with the soldiers he had left and to help those in the East as best he could; but he was held back by his counsellors, by ignorance of the enemy's numbers, and by the disarray of the forces with the kouropalates. So against his will he stayed in the palace.",
     "note": "Chonai (near Honaz, in western Anatolia) had the great pilgrimage church of St Michael, where the Archangel was said to have split the rock to divert a flood: the refugees drowned in the miracle's own chasm. In the game: 'A year at home?'; staying home here is the counsellors' advice, not the emperor's wish. Printed ἀνερεύξασθαι; the codex has ἀναρρεύξασθαι."},
    {"pg": "141.15–142.21", "titel": "The Turkish commander who came over",
     "orig": "Ἡμερῶν δὲ διαγενομένων τινῶν ἑτέρα τις φήμη τὸν βασιλέα καὶ τὸ Ῥωμαϊκὸν ἀνεκτήσατο. ἦν γὰρ ὅτε ὁ τῶν Τούρκων ἡγούμενος καὶ καταπολεμήσας τὸ ἡμέτερον στράτευμα καὶ τὸν στρατὸν ὑποχείριον ποιησάμενος, ὃν πολλῶν ταλάντων πρίασθαι οἱ τοῦ γένους αὐτοῦ παρεσκεύασαν, προσέρχεται τῷ βασιλεῖ μόνος μετὰ τοῦ στρατηγοῦ, φιλῶν οἰκέτης μᾶλλον εἶναι τοῦ βασιλέως ἢ στρατάρχης τῶν Οὔννων γνωρίζεσθαι. καὶ ὁ λόγος εἰς ἔργον ἐκβέβηκεν· ἐλήλυθε γὰρ ἔχων μεθ᾽ ἑαυτοῦ τὸν εἰρημένον τοῦ στρατοῦ προεξάρχοντα, ὃς καὶ τῇ βασιλίδι ἐπιδεδήμηκε, τὸ οἰκεῖον πλῆθος καταλιπὼν καὶ τὴν αὐτομολίαν αἱρετισάμενος ἀπροαίρετον. καὶ ἡ αἰτία, ὅτι περ ὁ σουλτάνος ὁ τῆς Περσίας κρατῶν, δυσμενῶς ἔχων πρὸς τοῦτον ὡς ἀποστάτην, στρατιὰν κατ᾽ αὐτοῦ καὶ ἀγελάρχην ἀπέστειλεν· ὧν τῷ φόβῳ κατασεισθεὶς οὐκ ἄλλως διαδρᾶναι τὸν κίνδυνον διεσκόπησεν ἢ τῷ προσφυγεῖν τῷ βασιλεῖ τῶν Ῥωμαίων. ὃ δὴ καὶ κατὰ νοῦν αὐτῷ προκεχώρηκεν· ὑπεδέχθη μὲν γάρ, καὶ ἀσινὴς τῷ οἴκῳ τοῦ διασωθέντος παρ᾽ αὐτοῦ κουροπαλάτου προσεδέχθη. ὁ δὲ βασιλεὺς οὐκ εὔθετος αὐτῷ κατεφάνη, μὴ κατ᾽ ὄψιν αὐτὸν ἀγαγὼν δι᾽ ἡμερῶν οὐκ ὀλίγων. εἶτα τῆς συγκλήτου συνάθροισιν μετὰ τῆς συνήθους λαμπροφορίας ποιησάμενος ὁρᾷ τοῦτον ἐν τῷ χρυσοτρικλίνῳ περὶ τὴν τοῦ ἡλίου ἐπιτολήν. τότε δὲ πάντες οἱ συνιόντες καὶ τὸ διανοητικὸν εἴτ᾽ οὖν αἰσθητικὸν ἰσχυρότερον ἔχοντες ἐπὶ μεῖζον τὴν φωνὴν ἦραν καὶ τὸ πάθος ἐξῆραν ὡς τὸ εἰκός· νέος μὲν γὰρ ἦν ὁ φανείς, πυγμαῖος δὲ τὴν ἡλικίαν σχεδόν, τὴν ὄψιν Σκύθης καὶ ἄχαρις, ἐπειδὴ καὶ τοῦτο τὸ γένος ἐκ Σκυθῶν καὶ τῆς ἐκείνων κακοηθείας καὶ δυσμορφίας κατάγεται. τιμήσας δὲ τοῦτον ὁ βασιλεὺς πρόεδρον, καὶ συμβαλέσθαι τοῦτον πρὸς τὴν κατὰ τῶν Τούρκων ἐκστρατείαν οὐ μικρῶς οἰηθείς, ἐξ ἐκείνου διεῖπεν αὐτόν.",
     "en": "After some days another report revived the emperor and the Romans. The leader of the Turks, the man who had beaten our army and taken our general captive (the general whom his kin had been preparing to ransom for many talents), was coming to the emperor alone, with the general, preferring to be the emperor's servant rather than to be known as commander of the Huns. And the word came true: he arrived bringing with him the said commander of the army, and he came to the capital, leaving his own people behind and choosing a desertion he had not wished for. The reason was that the sultan who rules Persia, hostile to him as a rebel, had sent an army and a chief against him; shaken by fear of them, he saw no other way of escaping the danger than to take refuge with the emperor of the Romans. This turned out as he intended: he was received, and taken in unharmed at the house of the kouropalates whom he had spared. But the emperor did not seem well disposed to him, and did not bring him before him for many days. Then, holding an assembly of the senate with the usual splendour, he saw him in the Chrysotriklinos at sunrise. At that everyone present who had stronger powers of thought or feeling raised their voices and let their feelings out, as was natural: the man who appeared was young, almost a pygmy in stature, Scythian and graceless to look at, since this people too descends from the Scythians and their malice and ugliness. The emperor honoured him with the rank of proedros, and thinking he would contribute not a little to the campaign against the Turks, kept him close from then on.",
     "note": "The Byzantine sources call him Chrysoskoulos; he was Erisgen, the sultan's brother-in-law, and Matthew of Edessa's emir Guedridj, 'of the family of the sultan', who went over to Constantinople (Matt. Sultan [1]) and later spoke for the Armenians in the emperor's council (Matt. Battle [2]). The kouropalates he had captured and brought with him is Manuel Komnenos. Attaleiates' description of him is the senators' contempt, and his own."},
]

DEPARTURE = [
    {"pg": "142.22–143.7", "titel": "The muster, the Sunday of Orthodoxy, and the court's pay",
     "orig": "Καὶ τὴν ἐν τῇ βασιλευούσῃ παραχειμασίαν τελέσας κατάλογον στρατιωτῶν ἐπεποίητο, καὶ διαπεραιωθεὶς ἄρτι τοῦ ἔαρος ὑπανοίγοντος, περὶ αὐτὴν τὴν ἡμέραν τῆς ἐπισήμου λεγομένης ὀρθοδοξίας, ἐν ᾗ φυλοκρινεῖν τοὺς αἱρετικοὺς ἀπὸ τῶν ὀρθοδόξων καὶ ἀναθέματι καθυποβάλλειν τοὺς ἑτεροδόξους τῇ ἐκκλησίᾳ νενόμισται, εἰς τὰ τῶν Ἠρίων παλάτια κατὰ τὸ ἔθος προσώρμησε, τῇ πρὸ αὐτῆς ἡμέρᾳ τὴν ἐτησίαν φιλοτιμίαν τὴν λεγομένην ῥόγαν τοῖς μεγιστᾶσι τῆς βουλῆς καταθέμενος.",
     "en": "Having spent the winter in the capital, he held a muster of soldiers, and as spring was just opening he crossed over, about the very day of the feast called Orthodoxy, on which it is the custom of the Church to separate the heretics from the orthodox and to put those of other beliefs under anathema; and as usual he landed at the palace of Hieria, having paid the leading men of the senate, the day before, the annual bounty called the roga.",
     "note": "The Sunday of Orthodoxy, first Sunday of Lent, fell on 13 March in 1071: the usual date given for the departure. The roga is the court's annual pay, which Romanos had cut in earlier years (the game's card 'The officials' pay'); here he pays it before he leaves. Hieria was an imperial palace on the Asian shore near Chalcedon."},
    {"pg": "143.8–143.24", "titel": "A dark dove, and the empress's farewell",
     "orig": "Διαπεραιουμένου δ᾽ αὐτοῦ τὸν Χαλκηδόνιον πορθμὸν περιστερά τις ποθὲν ἱπταμένη οὐ πάνυ τι λευκή, πρὸς τὸ μέλαν δὲ τὸ πλεῖστον αὑτῆς ὑποφαίνουσα, τὴν φέρουσαν τὸν βασιλέα νῆα ἐπήρχετο, ἕως εἰς αὐτὸν ἐκεῖνον καθεσθεῖσα χερσὶ ταῖς αὐτοῦ προσερρύη· κἀκεῖνος ταύτην τῇ βασιλίδι ἀνέπεμψε, περὶ αὐτὰ τὰ ἀνάκτορα τῆς πόλεως παρὰ τὸ εἰωθὸς ἐπιμεινάσῃ. τοῦτο δὲ σύμβολον ἐδόκει μελλούσης τινὸς ἀποβάσεως, οὐκ ἰσότητος δὲ καὶ ὁμοφωνίας τοῖς τοῦτο συμβάλλουσιν ἐδίδου παράθεσιν, ἀλλ᾽ οἱ μὲν πρὸς τὸ κρεῖττον οἱ δὲ πρὸς τὸ χεῖρον τὴν ἔκβασιν προεσήμαινον. ἡ δὲ βασιλὶς εἰ καὶ ἀμφίβολος τῷ βασιλεῖ καὶ ἀσύμβατος ἦν ἐν τῇ προπομπῇ καὶ οἷον ἀμφήριστος ἔκ τινων τοῖς συνοικοῦσιν ἐπισυμβαινουσῶν θρύψεων, ἀλλά γε τῇ πρὸς τὸν ἄνδρα στοργῇ καταπονηθεῖσα πρὸς τοῦτον εἰς τὴν ἐπιοῦσαν διεπεπεραίωτο, καὶ πρὸς ἡμέρας τινὰς καρτερήσασα καὶ τὸν συντακτήριον λόγον καὶ τρόπον ἀποσεμνύνασα νόστου τε ἐμνήσθη, κἀκεῖνον εἰς τὴν ἑῴαν μετὰ τῶν εἰωθότων προπεμπτηρίων ἀπέλυσεν.",
     "en": "As he was crossing the strait of Chalcedon, a dove came flying from somewhere, not at all white, but showing mostly black, towards the ship carrying the emperor, until it settled on the emperor himself and slipped into his hands. He sent it to the empress, who, against custom, had stayed behind in the palace of the City. This seemed a sign of some outcome to come, but it gave those who read it no agreement or concord: some foretold that the outcome would be better, others worse. The empress, though she had been doubtful and at odds with the emperor about seeing him off, and as it were quarrelsome because of some of the grievances that arise between people who live together, was overcome by her love for her husband and crossed over to him the next day; and after staying some days and honouring the farewell with words and ceremony, she remembered to return home, and sent him off to the East with the customary send-off.",
     "note": "The dove, black rather than white, goes to Eudokia: the empress who in the autumn would order the provinces not to receive him (Att. Coup [2]). Attaleiates records a marriage in trouble and a reconciliation on the shore."},
    {"pg": "144.1–144.17", "titel": "Helenopolis, 'the pitiful city'",
     "orig": "Ἔσχεν οὖν κἀνταῦθα καινόν τινα καὶ παρὰ τὸ εἰθισμένον ἡ τοῦ βασιλέως διαπεραίωσις ὅρμον· οὐ γὰρ ἐν ταῖς πύλαις καὶ τοῖς βασιλείοις δόμοις ὁ βασιλεὺς προσωρμίσατο, οὐδ᾽ ἐν νέων κώμῃ χωρίῳ τινὶ χωρητικῷ βασιλικῆς δορυφορίας ἢ ὑπατείας, ἀλλ᾽ εἰς Ἑλενόπολιν αὐτῷ τὸ σύνθημα τῆς ἀποβάσεως γέγονεν, ὅπου καὶ ἡ βασίλειος σκηνὴ προδιωρίσθη καὶ προεπήγνυτο, Ἑλενόπολιν τὴν προδιατεθεῖσαν τοῖς εὔφροσιν ἐκ τῆς προσηγορίας ἐλεεινόπολιν. οὐδὲ γὰρ αὐτὸ τοῦτο, τὸ ἀπὸ τῶν Ἠρίων εἰς Ἑλενόπολιν τὸν βασιλέα μεθαρμόσασθαι τὴν ἑῴαν ἀπόβασιν, ὁ οἰωνὸς ἀγαθὸς τοῖς ἀκριβοῦσιν ἐδόκει τὰ πράγματα· καὶ τί γὰρ ἔτι τῆς βασιλείου σκηνῆς ἱσταμένης κατεαχθὲν τὸ ὑποστηρίζον αὐτὴν ξύλον πεσεῖν ταύτην αἰφνηδὸν παρεσκεύασεν, ὡς μὴ ἀπᾴδειν τῷ τοῦ τόπου ὀνόματι τὴν τοῦ βασιλέως ἐν αὐτῷ ἐπισκήνωσιν; ἀλλ᾽ ἡ τῶν νῦν ἀνθρώπων συνήθης ἀβελτηρία καὶ καχεξία, καὶ τὸ ἐν τῇ δοκούσῃ πίστει ἄπιστον καὶ ἀσύμβλητον, ἀνάλγητον καὶ τοῦτο καὶ ἀπολυπραγμόνητον εἴασε.",
     "en": "So here too the emperor's crossing had a new and unusual landing-place: the emperor did not put in at the gates and the imperial residences, nor at a new village or some place able to hold the imperial guard or the officials, but the word was given for him to land at Helenopolis, where the imperial tent had been set out and pitched beforehand: Helenopolis, which the thoughtful had already read from its name as Eleeinopolis, 'the pitiful city'. For this very thing, the emperor's shifting his landing in the East from Hieria to Helenopolis, did not seem a good omen to those who look closely at affairs. And what of this: while the imperial tent was still standing, the pole holding it up broke and made it fall suddenly, so that the emperor's encampment there should not be out of tune with the name of the place? But the usual folly and ill disposition of people nowadays, and the faithlessness and incomprehension inside what passes for faith, let this too pass without pain or inquiry.",
     "note": "The pun turns Helenopolis, named for the mother of Constantine the Great, into 'pitiful city' (ἐλεεινή). The first omen of the march in Attaleiates' sequence: the dove, the tent, the fire, the donkey (Att. March [7]), the Gospel (Att. Battle [2]), the cross given to the envoys (Att. Battle [9]). Codex: προδιατηθεῖσαν."},
    {"pg": "144.18–145.18", "titel": "The fire that burned the emperor's horses",
     "orig": "Προῄει τοίνυν ὁ βασιλεὺς καὶ τῆς ἑῴας ἀποτέρω προήρχετο, ἕως εἰς τὴν τῶν Ἀνατολικῶν λεγομένην ἐπαρχίαν εἰσέβαλε, νῦν μᾶλλον ἤπερ τὸ πρότερον φειδωλίᾳ περὶ πάντας τοὺς ἀμφ᾽ αὐτὸν συνεχόμενος. ἐάσας οὖν τὸ ἐπὶ πεδίων πυροφόρων κατασκηνῶσαι, τῷ περιρρέοντι ταῦτα ποταμῷ προστιθεμένων, πρός τι ἄναντες καὶ τραχὺ χωρίον τὴν ἰδίαν κατασκήνωσιν ἐποιήσατο, δωματίοις ἐπιστέγοις ἐπιγαννύμενος, καὶ φεύγων τὴν ἐκ τῆς σκηνοπηγίας ἐνσκήνωσιν. ἔνθα δή τι καὶ συνέβη τῶν προτέρων οὐκ ἔλαττον εἰς κακοδαιμονίας οἰώνισμα. πῦρ γάρ ποθεν ἐναχθὲν τοὺς δόμους ἐκείνους, ἐν οἷς ὁ βασιλεὺς ἐγκατῴκιστο, μετὰ πολλῆς τῆς ἠχῆς ἐξαφθὲν κατενέμετο. καὶ πολλοὶ μὲν συνέδραμον εἰς τὴν αὐτοῦ κατάσβεσιν καὶ ἀπόπαυσιν, ὀλίγον δέ τι τοῖς βασιλικοῖς παρεβοήθησαν πράγμασιν· οἱ γὰρ τοῦ βασιλέως ἵπποι, ὅσοι τὰ πρῶτα τῶν ἄλλων ἐκέκτηντο, καὶ τὰ τῶν ὅπλων τιμιώτερα καὶ χαλινοὶ καὶ ὀχήματα βρῶσις ὁμοῦ τοῦ πυρὸς γεγόνασι καὶ κατάποσις. μόλις δ᾽ οὖν ἠδυνήθησάν τινα τῶν ἄλλων ἀποφυγεῖν τὴν τοῦ πυρὸς ἐρωήν. ἕτεροι δὲ τῶν ἵππων καὶ ἡμιόνων ἡμίφλεκτοι γεγονότες ἐβάδιζον ἐν τῇ στρατιᾷ, οὐδὲν λυσιτελὲς παρεχόμενοι, μαρτυρίαν δὲ διεμφαίνοντες τῆς ἐν τοῖς βασιλείοις προσγενομένης κακότητος καὶ τῆς συμβολικῆς ἐν ἅπασι διαθέσεως.\nἈλλὰ ταῦτα μὲν ὕστερον τὸ ἀποτέλεσμα συνεπέραινεν·",
     "en": "So the emperor went forward and advanced further into the East, until he entered the province called the Anatolikon, held now more than before by thrift towards everyone around him. Leaving the others to camp on the wheat-bearing plains that lie along the river flowing round them, he made his own quarters on a steep and rough spot, taking his pleasure in roofed rooms and avoiding a lodging in the tented camp. There something happened that was no less an omen of ill fortune than the earlier ones. A fire, brought from somewhere, caught those buildings in which the emperor had lodged, blazed up with a great roar and consumed them. Many ran to put it out and stop it, but they could help the imperial property very little: the emperor's horses, the best of all, the more precious of his arms, the bridles and the carriages became food and drink for the fire together. Some of the rest barely escaped the rush of the flames. Other horses and mules, half-burned, went along with the army, of no use at all, but showing a testimony of the evil that had befallen the imperial household and of the ominous disposition of everything.\nBut these things the outcome fulfilled later.",
     "note": "Attaleiates' critique is quiet but plain: the emperor lodges apart from his army, in houses rather than a tent, and is thriftier than before towards those around him."},
    {"pg": "145.18–146.12", "titel": "The Sangarios, the emperor's estates, the Halys",
     "orig": "ὁ δὲ βασιλεὺς διαπεραιωθεὶς τὸν Σαγγάρην ποταμὸν διὰ τῆς τοῦ Ζόμπου καλουμένης γεφύρας, ἤρξατο τὰς ὑπολειπομένας συναθροίζειν δυνάμεις· ἦσαν γὰρ οἱ τῆς στρατιᾶς διεσκεδασμένοι κατὰ λόφους καὶ σήραγγας καὶ κρησφύγετά τινα καὶ ἄντρα διὰ τὴν προδεδηλωμένην τῶν βαρβάρων ἐπίτασιν. καταλέξας δ᾽ οὖν ὅσους αὐτῷ βουλομένῳ ἐνῆν, πλείστους δ᾽ ἀποπεμψάμενος, τῆς εἰς τὰ πρόσω πορείας εὐθυμότερον εἴχετο, διαφόρως ἀποξενῶν ἑαυτὸν τοῦ στρατοῦ εἰς τὰς οἰκείας ἐπαύλεις καὶ κτημάτων ἐπιδείξεις οἰκείων καὶ πολυτελεστέρων οἰκοδομῶν διατάξεις. διαπεραιωθέντος οὖν τοῦ στρατοῦ τὸν Ἅλυν λεγόμενον ποταμὸν αὐτὸς οὐ συνδιεπεραιώθη τηνικαῦτα αὐτῷ, ἀλλ᾽ εἰς νεοπαγὲς φρούριον, ἐκ προστάξεως αὐτοῦ συνοικοδομηθέν, ἐπιμείνας ἐκεῖθέν τινας ἡμέρας διέτριψεν. εἶτα διαπεραιωθεὶς καὶ αὐτός, κἀν τῇ τοῦ Χαρσιανοῦ ἐπαρχίᾳ, τὴν διαίρεσιν ἐκ τοῦ στρατοῦ εἰς κτήσεις οἰκείας συνδιεγράψατο· καὶ τὸ ἀπ᾽ ἐκείνου ἀδιαίρετος ἦν, τῇ Καισαρέων μὴ προσμίξας τὸ σύνολον, ἕως εἰς τὴν λεγομένην Κρύαν πηγὴν ἐνηυλίσατο.",
     "en": "The emperor crossed the Sangarios river by the bridge called Zompos and began to gather the remaining forces; for the men of the army were scattered over hills and caves and some hiding-places and grottoes because of the pressure of the barbarians described above. He enrolled as many as he wished, sent most away, and pressed on with the march more cheerfully, estranging himself from the army in various ways, for his own country houses, displays of his own estates and the laying-out of more costly buildings. When the army crossed the river called the Halys, he did not cross with it then, but stayed some days in a newly built fort, raised on his orders, and spent the time there. Then he too crossed, and in the province of Charsianon marked out his leave from the army for his own properties; from then on he was not apart from it, not going to Caesarea at all, until he camped at the place called Kryapege.",
     "note": "Romanos was a Cappadocian landowner, and the march went through his own country. 'Sent most away' means the soldiers he found unfit. Kryapege, 'Cold Spring', was a regular muster-place of Byzantine armies."},
    {"pg": "146.12–147.15", "titel": "Cold Spring, and the German guard",
     "orig": "ἔστι γὰρ ὁ τόπος οὐδενὸς τῶν χρηστῶν τὸ παράπαν ἀπολειπόμενος, τό τε [τὸ] ὕδωρ διειδὲς ἅμα καὶ πότιμον καὶ ψυχρότατον, δένδρα τε συνηρεφῆ μετὰ δαψιλοῦς τῆς πόης ἐκτρέφον καὶ ξυλίσασθαι εὔπορος, παντοίοις τε ῥόδοις κατάκομος καὶ κρινωνιαῖς, λόφοις τε ἠρέμα πρὸς ἑαυτοὺς ἀνάγουσιν εὔθετος, καὶ οἷον εἰπεῖν ἀστυκώμη καὶ ἀγρόπολις διὰ τῆς συμμιγοῦς ποριμότητος γνωριζόμενος. ἐκεῖσε δ᾽ ὁ βασιλεὺς ἡμέρας τινὰς στρατοπεδευσάμενος, ὡς εἶδε τὴν χώραν ἀφειδῶς κατακειρομένην ἐκ τῶν στρατιωτῶν καὶ μᾶλλον ἐκ τοῦ μισθοφορικοῦ καὶ ἀλλογενοῦς, καὶ ἅπαν λήϊον ἐξώρως ἀποτεμνόμενον καὶ τοῖς βοσκήμασι λαφυραγωγούμενον, δηχθεὶς τὴν ψυχὴν ἀπηνέστερον προσηνέχθη τισὶ τῶν Νεμίτζων λεγομένων, οὓς ὁ παλαιὸς λόγος Σαυρομάτας καὶ αὐτοὺς ἐγίνωσκεν. Ἀλλ᾽ οἵγε θράσει καὶ θυμῷ ζέοντες καὶ ἀπονοίᾳ βαρβαρικῇ πρὸς ἐκδίκησιν τῶν ἰδίων ἰταμῶς διανέστησαν, καὶ τῶν ἵππων περὶ τὴν τῶν ἀριστῶν ἐπιβάντες ὥραν τῆς τοῦ βασιλέως σκηνῆς καὶ αὐτοῦ βασιλέως κατεξαναστῆναι συνέθεντο. γνωσθείσης δὲ τῆς αὐτῶν ἐπιθέσεως βοή τε περὶ τὸ στρατόπεδον γέγονε, καὶ ταχὺ διαβοηθέντος τοῦ πράγματος συνέστη μὲν ὁ βασιλεὺς καὶ διηυτρεπίσθη τὰ πρὸς τὸν πόλεμον, ἐπιβὰς δὲ τοῦ ἵππου καὶ τὴν στρατιὰν ὡς εἰς μάχην συναρμοσάμενος κατέπληξε τοὺς ἰδιοξένους, εἰς τὸ πεδίον εὐσυντάκτως γενόμενος· καὶ ὑποσπόνδους αὐτοὺς ποιησάμενος, τὴν ἐσχάτην τούτοις χώραν ἐκ τῆς σωματοφυλακίας καὶ τῆς πρώην ἐγγύτητος ἀπενείματο, ἐν τούτῳ καὶ μόνῳ τὸ πρόστιμον αὐτοῖς τοῦ τοιούτου ἐγκλήματος ἐγκαταθέμενος.",
     "en": "For the place lacks nothing useful at all: water clear, good to drink and very cold; it grows shady trees with abundant grass and is well supplied with firewood; it is thick with roses of every kind and with lilies, well placed among hills that rise gently towards one another, and known, one might say, as a village-town and a country-city for its mingled plenty. The emperor camped there some days; and when he saw the country being shorn without mercy by the soldiers, above all by the mercenaries and foreigners, and all the crops cut before their time and carried off as plunder for the animals, he was stung to the soul and dealt harshly with some of the so-called Nemitzoi, whom the ancient account knew as Sauromatai too. But they, boiling with rashness and anger and barbarian madness, rose up recklessly to avenge their own, mounted their horses about the hour of the midday meal, and agreed to rise against the emperor's tent and the emperor himself. When their attack became known, a shout went up round the camp, and as the news spread quickly the emperor stood up and made ready for battle; mounting his horse and arranging the army as if for battle, he struck fear into these household foreigners, appearing on the plain in good order. He brought them to terms, and assigned them the last place, away from the bodyguard and their former nearness to him: in this alone he set their punishment for such an offence.",
     "note": "The Nemitzoi are Germans (Slavonic němьci) of the imperial guard: the game's 'guard' contingent. The plundered harvest is the game's pool card 'The soldiers and the harvest', which now cites this passage. Bekker queries ἀριστᾶν. The emperor's severity with the Germans foreshadows his severity with the donkey thief (Att. March [7])."},
    {"pg": "147.16–148.2", "titel": "The dead on the road from Sebasteia",
     "orig": "Ἐκεῖθεν δ᾽ εἰς Σεβάστειαν καὶ τὰ πρόσω κεχωρηκὼς ἀπήει τὴν τῶν Ἰβήρων καταλαβεῖν ἐπειγόμενος, ὅτε καὶ δύο ἀτραπῶν ἐκ Σεβαστείας διαιρουμένων καὶ εἰς τὸ θέμα Κολωνείας συναγουσῶν τὴν ἐν ἀριστερᾷ πορευθῆναι θελήσας ὁ βασιλεὺς πολλῶν πτωμάτων θέαν ἀνθρωπίνων προσέλαβεν. ἐν ἐκείνῳ γὰρ τῷ τόπῳ συνέστη τῷ παρελθόντι ἔτει ὁ πόλεμος τοῖς τε Ῥωμαίοις καὶ τοῖς Τούρκοις στρατηγοῦντος Μανουὴλ κουροπαλάτου τοῦ Κομνηνοῦ, καὶ τὸ Ῥωμαϊκὸν ἡττήθη στρατόπεδον. ἐφάνη δὲ καὶ τοῦτο τοῖς στρατοπεδευομένοις οὐκ εὔθετον θέαμα.",
     "en": "From there he went on to Sebasteia and beyond, hurrying to reach the land of the Iberians; and when, of two roads that divide at Sebasteia and both lead into the theme of Koloneia, the emperor chose to take the left-hand one, he came upon the sight of many human corpses. For in that place, the year before, the battle had been fought between the Romans and the Turks under the command of Manuel Komnenos the kouropalates, and the Roman army had been beaten. This too seemed to the soldiers an ill-fitting sight.",
     "note": "The dead of 1070 (Att. 1070 [3]). Matthew of Edessa has the emperor sack Sebasteia at this stage and threaten the Armenian faith (Matt. Battle [1]); Attaleiates passes through the town without a word of it. The next unit is Att. March [1], Theodosiopolis."},
]

SECTIONS_PRE = [
    {"id": "prelude", "zk": "Att. 1070", "titel": "The year 1070",
     "blurb": "The emperor stays in the capital and sends Manuel Komnenos east; the church of the Blachernai burns; a young general's victories meet the emperor's inscrutable face; defeat near Sebasteia, the sack of Chonai and its drowned refugees; and the Turkish commander who beat Manuel comes to Constantinople with his prisoner to serve the emperor.",
     "units": PRELUDE},
    {"id": "departure", "zk": "Att. Dep.", "titel": "The departure of 1071",
     "blurb": "March 1071: the court is paid and the army crosses to Asia on the Sunday of Orthodoxy; a dark dove flies into the emperor's hands; the empress comes to say goodbye; the tent collapses at Helenopolis, 'the pitiful city'; fire burns the emperor's best horses; the march through his own estates; roses and lilies at Cold Spring and a mutiny of the German guard; and the dead of last year's battle on the road from Sebasteia.",
     "units": DEPARTURE},
]
