"""Edward Gibbon, The History of the Decline and Fall of the Roman Empire,
chapter LVII, the passage on Romanos Diogenes and Alp Arslan, in the first
(quarto) edition: volume V (London: Strahan and Cadell, 1788), pp. 660-668.

Internet Archive bim_eighteenth-century_the-history-of-the-decli_gibbon-
edward_1788_5_0 (printed page n = leaf n+13). The text was set from Project
Gutenberg's etext (#735, the Milman edition) and corrected, word by word,
against the 1788 OCR and then every page image. The Gutenberg text departs
from 1788 in spelling (valor, recall, cimeter, negotiation) and in a few
readings: 'Romulus led his army' for Romanus, 'spent' for 'wasted', 'the
national custom' for 'a national custom', 'forgot' for 'forget', and in
note 37 it has lost Gibbon's Greek, turning Bryennios' 'not unworthy of the
empire of the Romans' into 'the terms were bad'. Here 1788 is followed
throughout: its spelling (valour, recal, scymetar, negociation, Musulman,
bigotted) is kept, the long s is printed as s, the capitals of the epitaph
are kept. Gibbon's footnotes on the passage (30-40) are given in the notes
of each unit, as 'Gibbon's note'; his marginal headings are the unit titles
where they fall. The text is English: no translation.

Each unit: pg (1788 page), titel, en, note (optional)."""

BATTLE = [
    {"pg": "660–661", "titel": "The emperor Romanus Diogenes",
     "en": "The false or genuine magnanimity of Mahmud the Gaznevide, was not imitated by Alp Arslan; and he attacked without scruple the Greek empress Eudocia and her children. His alarming progress compelled her to give herself and her sceptre to the hand of a soldier; and Romanus Diogenes was invested with the Imperial purple. His patriotism, and perhaps his pride, urged him from Constantinople within two months after his accession; and the next campaign he most scandalously took the field during the holy festival of Easter. In the palace, Diogenes was no more than the husband of Eudocia: in the camp, he was the emperor of the Romans, and he sustained that character with feeble resources and invincible courage. By his spirit and success, the soldiers were taught to act, the subjects to hope, and the enemies to fear. The Turks had penetrated into the heart of Phrygia; but the sultan himself had resigned to his emirs the prosecution of the war; and their numerous detachments were scattered over Asia in the security of conquest. Laden with spoil and careless of discipline, they were separately surprised and defeated by the Greeks: the activity of the emperor seemed to multiply his presence; and while they heard of his expedition to Antioch, the enemy felt his sword on the hills of Trebizond.",
     "note": "Gibbon's marginal heading: 'The emperor Romanus Diogenes, A.D. 1068–1071.' The 'holy festival of Easter' is the start of the campaign of 1069; Attaleiates, who was there, dates the departure of 1071 to the Sunday of Orthodoxy in Lent (Att. Dep. [1])."},
    {"pg": "661–662", "titel": "The army of 1071",
     "en": "In three laborious campaigns, the Turks were driven beyond the Euphrates: in the fourth and last, Romanus undertook the deliverance of Armenia. The desolation of the land obliged him to transport a supply of two months provisions; and he marched forwards to the siege of Malazkerd, an important fortress in the midway between the modern cities of Arzeroum and Van. His army amounted, at the least, to one hundred thousand men. The troops of Constantinople were reinforced by the disorderly multitudes of Phrygia and Cappadocia; but the real strength was composed of the subjects and allies of Europe, the legions of Macedonia, and the squadrons of Bulgaria; the Uzi, a Moldavian hord, who were themselves of the Turkish race; and, above all, the mercenary and adventurous bands of French and Normans. Their lances were commanded by the valiant Ursel of Baliol, the kinsman or father of the Scottish kings, and were allowed to excel in the exercise of arms, or, according to the Greek style, in the practice of the Pyrrhic dance.",
     "note": "Gibbon's note 30: Malazkerd is the Mantzikierte of Constantine Porphyrogenitus and the Byzantines of the eleventh century; Abulfeda 'describes Malasgerd as a small town, built with black stone, supplied with water, without trees, &c.' Note 32: 'Urselius (the Russelius of Zonaras)' is Roussel de Bailleul; the descent of the Scottish Balliols from him is a flourish of Gibbon's, after Malaterra and Ducange. The 'two months provisions' are Attaleiates' (Att. March [1]); Romanos made three campaigns, 1068, 1069 and 1071, not four."},
    {"pg": "662–663", "titel": "Defeat of the Romans: the peace refused",
     "en": "On the report of this bold invasion, which threatened his hereditary dominions, Alp Arslan flew to the scene of action at the head of forty thousand horse. His rapid and skilful evolutions distressed and dismayed the superior numbers of the Greeks; and in the defeat of Basilacius, one of their principal generals, he displayed the first example of his valour and clemency. The imprudence of the emperor had separated his forces after the reduction of Malazkerd. It was in vain that he attempted to recal the mercenary Franks: they refused to obey his summons; he disdained to await their return: the desertion of the Uzi filled his mind with anxiety and suspicion; and against the most salutary advice he rushed forwards to speedy and decisive action. Had he listened to the fair proposals of the sultan, Romanus might have secured a retreat, perhaps a peace; but in these overtures he supposed the fear or weakness of the enemy, and his answer was conceived in the tone of insult and defiance. \"If the Barbarian wishes for peace, let him evacuate the ground which he occupies for the encampment of the Romans, and surrender his city and palace of Rei as a pledge of his sincerity.\"",
     "note": "Gibbon's marginal heading: 'Defeat of the Romans, A.D. 1071, August.' Gibbon's note 33: 'Elmacin assigns this probable number [forty thousand], which is reduced by Abulpharagius to 15,000, and by d'Herbelot to 12,000 horse. … The Greeks abstain from any definition of numbers.' Ibn al-Athīr has fifteen thousand (IA Battle [2]); Abulpharagius is Bar Hebraeus, who worked from Michael the Syrian. The demand for Rei is Ibn al-Athīr's 'no truce except at Rayy' (IA Battle [4]), which Gibbon knew through Elmacin; the Greeks tell the refusal differently (Compare: the peace refused)."},
    {"pg": "663–664", "titel": "The battle, and the standard turned",
     "en": "Alp Arslan smiled at the vanity of the demand, but he wept the death of so many faithful Moslems; and, after a devout prayer, proclaimed a free permission to all who were desirous of retiring from the field. With his own hands he tied up his horse's tail, exchanged his bow and arrows for a mace and scymetar, clothed himself in a white garment, perfumed his body with musk, and declared that if he were vanquished, that spot should be the place of his burial. The sultan himself had affected to cast away his missile weapons; but his hopes of victory were placed in the arrows of the Turkish cavalry, whose squadrons were loosely distributed in the form of a crescent. Instead of the successive lines and reserves of the Grecian tactics, Romanus led his army in a single and solid phalanx, and pressed with vigour and impatience the artful and yielding resistance of the Barbarians. In this desultory and fruitless combat he wasted the greater part of a summer's day, till prudence and fatigue compelled him to return to his camp. But a retreat is always perilous in the face of an active foe; and no sooner had the standard been turned to the rear than the phalanx was broken by the base cowardice, or the baser jealousy, of Andronicus, a rival prince, who disgraced his birth and the purple of the Caesars. The Turkish squadrons poured a cloud of arrows on this moment of confusion and lassitude; and the horns of their formidable crescent were closed in the rear of the Greeks. In the destruction of the army and pillage of the camp, it would be needless to mention the number of the slain or captives. The Byzantine writers deplore the loss of an inestimable pearl: they forget to mention, that in this fatal day the Asiatic provinces of Rome were irretrievably sacrificed.",
     "note": "Gibbon's note 34: 'The Byzantine writers do not speak so distinctly of the presence of the sultan; he committed his forces to an eunuch, had retired to a distance, &c. Is it ignorance, or jealousy, or truth?' The eunuch is Bryennios' Taranges (Bry. Campaign [7]); the prayer, the horse's tail and the white shroud are Ibn al-Athīr's (IA Battle [5]). Note 35: Andronikos 'was the son of the Caesar John Ducas … Nicephorus Bryennius applauds his virtues and extenuates his faults … Yet he owns his enmity to Romanus, οὐ πάνυ δὲ φιλίως ἔχων πρὸς βασιλέα. Scylitzes speaks more explicitly of his treason.' The Greek is Bryennios' 'not at all friendly to the emperor' (Bry. Campaign [6]). Gibbon's 'standard turned to the rear' is Attaleiates' (Att. Battle [12]), and the name of this project's game. The last sentence is the verdict of 1788, a judgement the sources written within a decade do not yet make (Compare: who broke the army?)."},
]

CAPTIVE = [
    {"pg": "664", "titel": "Captivity and deliverance of the emperor",
     "en": "As long as a hope survived, Romanus attempted to rally and save the relics of his army. When the centre, the Imperial station, was left naked on all sides, and encompassed by the victorious Turks, he still, with desperate courage, maintained the fight till the close of day, at the head of the brave and faithful subjects who adhered to his standard. They fell around him: his horse was slain, the emperor was wounded; yet he stood alone and intrepid, till he was oppressed and bound by the strength of multitudes. The glory of this illustrious prize was disputed by a slave and a soldier; a slave who had seen him on the throne of Constantinople, and a soldier whose extreme deformity had been excused on the promise of some signal service.",
     "note": "Gibbon's marginal heading: 'Captivity and deliverance of the emperor.' The disputed prize joins two Arabic stories: the slave soldier whom Nizam al-Mulk had turned down in contempt, 'perhaps he will bring us the king of the Rum' (IA Battle [7]), and the slave who knew the emperor by sight. Michael the Syrian has a third: a nephew of the sultan, robbed of his prize by a soldier who was crucified for it (Mich. Battle [3])."},
    {"pg": "664–665", "titel": "The foot on the neck",
     "en": "Despoiled of his arms, his jewels, and his purple, Romanus spent a dreary and perilous night on the field of battle, amidst a disorderly crowd of the meaner Barbarians. In the morning the royal captive was presented to Alp Arslan, who doubted of his fortune, till the identity of the person was ascertained by the report of his ambassadors, and by the more pathetic evidence of Basilacius, who embraced with tears the feet of his unhappy sovereign. The successor of Constantine, in a plebeian habit, was led into the Turkish divan, and commanded to kiss the ground before the lord of Asia. He reluctantly obeyed; and Alp Arslan, starting from his throne, is said to have planted his foot on the neck of the Roman emperor. But the fact is doubtful; and if, in this moment of insolence, the sultan complied with a national custom, the rest of his conduct has extorted the praise of his bigotted foes, and may afford a lesson to the most civilized ages. He instantly raised the royal captive from the ground; and thrice clasping his hand with tender sympathy, assured him, that his life and dignity should be inviolate in the hands of a prince who had learned to respect the majesty of his equals and the vicissitudes of fortune.",
     "note": "Gibbon's note 36: 'This circumstance, which we read and doubt in Scylitzes and Constantine Manasses, is more prudently omitted by Nicephorus and Zonaras.' The foot on the neck is the Western legend of the Boccaccio manuscripts, where the emperor becomes the sultan's footstool (Plates); Attaleiates, who was there, has the sultan rise and embrace him, Ibn al-Athīr has three blows (Compare: the sultan and the captive). The 'report of his ambassadors' is Attaleiates' too: the envoys who had once come to the emperor identify him (Att. Capt. [2]). Gibbon's 'thrice clasping his hand' is his own reconciliation of embrace and blows."},
    {"pg": "665", "titel": "Eight days at the sultan's table",
     "en": "From the divan, Romanus was conducted to an adjacent tent, where he was served with pomp and reverence by the officers of the sultan, who, twice each day, seated him in the place of honour at his own table. In a free and familiar conversation of eight days, not a word, not a look, of insult, escaped from the conqueror; but he severely censured the unworthy subjects who had deserted their valiant prince in the hour of danger, and gently admonished his antagonist of some errors which he had committed in the management of the war. In the preliminaries of negociation, Alp Arslan asked him what treatment he expected to receive, and the calm indifference of the emperor displays the freedom of his mind. \"If you are cruel,\" said he, \"you will take my life; if you listen to pride, you will drag me at your chariot wheels; if you consult your interest, you will accept a ransom, and restore me to my country.\" \"And what,\" continued the sultan, \"would have been your own behaviour, had fortune smiled on your arms?\" The reply of the Greek betrays a sentiment, which prudence, and even gratitude, should have taught him to suppress. \"Had I vanquished,\" he fiercely said, \"I would have inflicted on thy body many a stripe.\" The Turkish conqueror smiled at the insolence of his captive; observed that the Christian law inculcated the love of enemies and forgiveness of injuries; and nobly declared, that he would not imitate an example which he condemned.",
     "note": "The eight days, the two meals and the reminder of 'some apparent mistakes' are Attaleiates' (Att. Capt. [3]), whom Gibbon read through Skylitzes, who copied him; so is the exchange: 'I would have used up your body with many blows', 'I will not imitate your harshness' (Att. Capt. [4]). The three answers, 'kill me, parade me, or ransom me', are Ibn al-Athīr's (IA Battle [8]). Each source has its own version of the emperor's reply: 'something ugly' (Ibn al-Athīr), 'burn you in the fire' (Michael the Syrian, Mich. Battle [4]). The sultan's lesson from 'the Christian law' is Gibbon's Enlightenment touch."},
    {"pg": "665–666", "titel": "The treaty, and two hundred thousand pieces",
     "en": "After mature deliberation, Alp Arslan dictated the terms of liberty and peace, a ransom of a million, an annual tribute of three hundred and sixty thousand pieces of gold, the marriage of the royal children, and the deliverance of all the Moslems who were in the power of the Greeks. Romanus, with a sigh, subscribed this treaty, so disgraceful to the majesty of the empire; he was immediately invested with a Turkish robe of honour; his nobles and patricians were restored to their sovereign; and the sultan, after a courteous embrace, dismissed him with rich presents and a military guard. No sooner did he reach the confines of the empire, than he was informed that the palace and provinces had disclaimed their allegiance to a captive: a sum of two hundred thousand pieces was painfully collected; and the fallen monarch transmitted this part of his ransom, with a sad confession of his impotence and disgrace. The generosity, or perhaps the ambition, of the sultan, prepared to espouse the cause of his ally; but his designs were prevented by the defeat, imprisonment, and death, of Romanus Diogenes.",
     "note": "Gibbon's note 37: 'The ransom and tribute are attested by reason and the Orientals. The other Greeks are modestly silent; but Nicephorus Bryennius dares to affirm, that the terms were οὐκ ἀναξίας Ῥωμαίων ἀρχῆς, and that the emperor would have preferred death to a shameful treaty.' The Greek is Bryennios' 'not unworthy of the empire of the Romans' (Bry. Coup [2]); the Gutenberg etext has lost it and prints 'the terms were bad', the opposite. Note 38 lists Gibbon's sources: Scylitzes, Zonaras, Bryennius, Glycas, Manasses, Elmacin, Abulpharagius, d'Herbelot, de Guignes. He had no Attaleiates, which was first printed in 1853. Ibn al-Athīr names a million and a half (IA Battle [9]); the two hundred thousand sent with 'a sad confession' are his too (IA Battle [10]). The sultan's readiness to help his ally answers Psellos' 'Persian help' (Psell. Civil [9])."},
]

SULTAN = [
    {"pg": "666–667", "titel": "Death of Alp Arslan",
     "en": "In the treaty of peace, it does not appear that Alp Arslan extorted any province or city from the captive emperor; and his revenge was satisfied with the trophies of his victory, and the spoils of Anatolia, from Antioch to the Black Sea. The fairest part of Asia was subject to his laws: twelve hundred princes, or the sons of princes, stood before his throne; and two hundred thousand soldiers marched under his banners. The sultan disdained to pursue the fugitive Greeks; but he meditated the more glorious conquest of Turkestan, the original seat of the house of Seljuk. He moved from Bagdad to the banks of the Oxus; a bridge was thrown over the river; and twenty days were consumed in the passage of his troops. But the progress of the great king was retarded by the governor of Berzem; and Joseph the Carizmian presumed to defend his fortress against the powers of the East. When he was produced a captive in the royal tent, the sultan, instead of praising his valour, severely reproached his obstinate folly; and the insolent replies of the rebel provoked a sentence, that he should be fastened to four stakes and left to expire in that painful situation. At this command the desperate Carizmian, drawing a dagger, rushed headlong towards the throne: the guards raised their battle-axes; their zeal was checked by Alp Arslan, the most skilful archer of the age; he drew his bow, but his foot slipped, the arrow glanced aside, and he received in his breast the dagger of Joseph, who was instantly cut in pieces.",
     "note": "Gibbon's marginal heading: 'Death of Alp Arslan, A.D. 1072.' 'It does not appear that Alp Arslan extorted any province or city': Gibbon, like the sources, sees no plan of conquest in Anatolia; the Turkmen who took it were not the sultan's army. Matthew of Edessa tells the death otherwise: a lord who came to submit, with two knives hidden in his sandals (Matt. Death [1])."},
    {"pg": "667–668", "titel": "'Repair to Maru'",
     "en": "The wound was mortal; and the Turkish prince bequeathed a dying admonition to the pride of kings. \"In my youth,\" said Alp Arslan, \"I was advised by a sage, to humble myself before God; to distrust my own strength; and never to despise the most contemptible foe. I have neglected these lessons; and my neglect has been deservedly punished. Yesterday, as from an eminence I beheld the numbers, the discipline, and the spirit, of my armies, the earth seemed to tremble under my feet; and I said in my heart, surely thou art the king of the world, the greatest and most invincible of warriors. These armies are no longer mine; and in the confidence of my personal strength, I now fall by the hand of an assassin.\" Alp Arslan possessed the virtues of a Turk and a Musulman; his voice and stature commanded the reverence of mankind; his face was shaded with long whiskers; and his ample turban was fashioned in the shape of a crown. The remains of the sultan were deposited in the tomb of the Seljukian dynasty; and the passenger might read and meditate this useful inscription: \"O YE WHO HAVE SEEN THE GLORY OF ALP ARSLAN EXALTED TO THE HEAVENS, REPAIR TO MARU, AND YOU WILL BEHOLD IT BURIED IN THE DUST!\" The annihilation of the inscription, and the tomb itself, more forcibly proclaims the instability of human greatness.",
     "note": "Gibbon's note 39: 'This interesting death is told by d'Herbelot and M. de Guignes from their Oriental writers; but neither of them have transfused the spirit of Elmacin.' Note 40: 'A critic of high renown, (the late Dr. Johnson,) who has severely scrutinized the epitaphs of Pope, might cavil in this sublime inscription at the words \"repair to Maru,\" since the reader must already be at Maru before he could peruse the inscription.' Maru is Merv."},
]

SECTIONS = [
    {"id": "battle", "zk": "Gibbon Battle", "titel": "The emperor and the battle",
     "blurb": "Gibbon in 1788, from the Byzantine chroniclers and the Arabic historians in Latin and French: Romanos 'in the palace no more than the husband of Eudocia: in the camp the emperor of the Romans'; the army of a hundred thousand; the peace refused; the sultan's white garment; the standard turned and 'the baser jealousy of Andronicus'; the Asiatic provinces 'irretrievably sacrificed'.",
     "units": BATTLE},
    {"id": "captive", "zk": "Gibbon Captive", "titel": "The captive emperor",
     "blurb": "A slave and a soldier dispute the prize; the foot on the neck, doubted; eight days at the sultan's table; 'many a stripe'; the treaty, and the two hundred thousand pieces.",
     "units": CAPTIVE},
    {"id": "sultan", "zk": "Gibbon Sultan", "titel": "The death of the sultan",
     "blurb": "The Oxus, Joseph the Carizmian and the slipped foot; a dying admonition to the pride of kings; the epitaph at Merv.",
     "units": SULTAN},
]
