"""Ibn al-Athir, al-Kamil fi l-ta'rikh, year 463 AH (1070-71), ed. Tornberg,
vol. X (Leiden: Brill, 1864), pp. 42-46.

Transcribed by eye from the page images (Internet Archive kamil-Tornberg,
vol-10 jp2 leaves 46-50), with the OCR (kamil-Tornberg-vol-10_djvu.txt) as a
first draft. Spelling as printed: Tornberg prints final ى for ي (فى), omits
most hamzas (القايم, ماية, دماكم) and writes بغداذ; this is kept. His
occasional vowel signs and shaddas are not carried; his asterisks and
footnote numbers are dropped, and his variant readings are given in notes
only where they touch the sense. The print has commas and a flower at the end
of each chapter; the units are the site's. English: the site's working
translation (CC0).

Each unit: pg (Tornberg vol. X page), titel, orig, en, note (optional)."""

ALEPPO = [
    {"pg": "X, 42–43", "titel": "Aleppo turns to Baghdad",
     "orig": "ثم دخلت سنة ثلاث وستين واربعماية\nذكر الخطبة للقايم بامر الله والسلطان بحلب\nفى هذه السنة خطب محمود بن صالح بن مرداس بحلب لامير المومنين القايم بامر الله وللسلطان الب ارسلان، وسبب ذلك انه راى اقبال دولة السلطان وقوتها وانتشار دعوتها فجمع اهل حلب وقال هذه دولة جديدة ومملكة شديدة ونحن تحت الخوف منهم وهم يستحلون دماكم لاجل مذاهبكم والراى ان نقيم الخطبة قبل ان ياتى وقت لا ينفعنا فيه قول ولا بذل، فاجاب المشايخ الى ذلك ولبس الموذنون السواد وخطبوا للقايم بامر الله والسلطان، فاخذت العامة حصر الجامع وقالوا هذه حصر على بن ابى طالب فليات ابو بكر بحصر يصلى عليها بالناس، وارسل الخليفة الى محمود الخلع مع نقيب النقباء طراد بن محمد الزينبى فلبسها، ومدحه ابن سنان الخفاجى وابو الفتيان بن حيوس، وقال ابو عبد الله بن عطية يمدح القايم بامر الله ويذكر الخطبة بحلب ومكة والمدينة\nكم طايع لك لم تجلب عليه ولم ... تعرف لطاعته غير التقى سببا\nهذا البشير باذعان الحجاز وذا ... داعى دمشق وذا المبعوث من حلبا",
     "en": "Then came the year four hundred and sixty-three.\nThe Friday sermon at Aleppo for al-Qa'im bi-amr Allah and the sultan.\nIn this year Mahmud ibn Salih ibn Mirdas had the Friday sermon at Aleppo pronounced in the name of the Commander of the Faithful al-Qa'im bi-amr Allah and of the sultan Alp Arslan. The reason was that he saw the rising fortune of the sultan's dynasty, its strength and the spread of its cause. He gathered the people of Aleppo and said: 'This is a new dynasty and a hard kingdom; we live in fear of them, and they hold your blood lawful because of your persuasions. The right course is to establish the sermon before a time comes when neither words nor money will help us.' The elders agreed. The muezzins put on black and the sermon was pronounced for al-Qa'im bi-amr Allah and the sultan. The common people took the mats of the great mosque and said: 'These are the mats of Ali ibn Abi Talib; let Abu Bakr bring mats of his own to lead the people in prayer on.' The caliph sent Mahmud robes of honour with the chief of the sharifs, Tirad ibn Muhammad al-Zaynabi, and he put them on. Ibn Sinan al-Khafaji and Abu l-Fityan ibn Hayyus praised him, and Abu Abd Allah ibn Atiyya said, praising al-Qa'im bi-amr Allah and speaking of the sermon at Aleppo, Mecca and Medina:\nHow many obey you whom you did not force, and whose obedience knew no cause but fear of God:\nthis herald brings the submission of the Hijaz, this one the call of Damascus, and this one is sent from Aleppo.",
     "note": "Aleppo was ruled by a Shi'i Arab dynasty, the Mirdasids, and its people were largely Shi'i; the Friday sermon had named the Fatimid caliph of Cairo. Black is the Abbasid colour. The mats joke sets Ali, the Shi'i imam, against Abu Bakr, the Sunni first caliph. The sultan's war in 463 is this one: for the Abbasid caliph against Fatimid Egypt."},
    {"pg": "X, 43–44", "titel": "The sultan before Aleppo",
     "orig": "ذكر استيلاء السلطان الب ارسلان على حلب\nفى هذه السنة سار السلطان الب ارسلان الى حلب وجعل طريقه على ديار بكر فخرج اليه صاحبها نصر بن مروان وخدمه بماية الف دينار وحمل اليه اقامة، عرف السلطان انه قسطها على البلاد فامر بردها، ووصل الى آمد فراها ثغرا منيعا فتبرك به وجعل يمر يده على السور ويمسح بها صدره، وسار الى الرها فحصرها فلم يظفر منها بطايل، فسار الى حلب وقد وصلها نقيب النقباء ابو الفوارس طراد بالرسالة القايمية والخلع، فقال له محمود صاحب حلب اسالك الخروج الى السلطان واستعفاء لى من الحضور عنده، فخرج نقيب النقباء واخبر السلطان بانه قد لبس الخلع القايمية وخطب، فقال اى شىء تساوى خطبتهم وهم يوذنون حى على خير العمل ولا بد من الحضور ودوس بساطى، فامتنع محمود من ذلك فاشتد الحصار على البلد وغلت الاسعار وعظم القتال، وزحف السلطان يوما وقرب من البلد فوقعت حجر منجنيق فى فرسه، فلما عظم الامر على محمود خرج ليلا ومعه والدته منيعة بنت وثاب النميرى فدخلا على السلطان وقالت له هذا ولدى فافعل به ما تحب، فتلقاهما بالجميل وخلع على محمود واعاده الى بلده فانفذ الى السلطان مالا جزيلا.",
     "en": "How the sultan Alp Arslan took Aleppo.\nIn this year the sultan Alp Arslan marched on Aleppo and made his way through Diyar Bakr. Its lord, Nasr ibn Marwan, came out to him and served him with a hundred thousand dinars and brought him provisions. The sultan learned that he had levied them on the country, and ordered them returned. He reached Amid, saw it to be an impregnable frontier fortress, and took blessing from it: he began to pass his hand over the wall and wipe his chest with it. He marched to Edessa and besieged it, but gained nothing from it; so he marched on Aleppo. The chief of the sharifs, Abu l-Fawaris Tirad, had arrived there with the caliph's letter and the robes. Mahmud, lord of Aleppo, said to him: 'I ask you to go out to the sultan and beg him to excuse me from coming before him.' The chief of the sharifs went out and told the sultan that Mahmud had put on the caliph's robes and pronounced the sermon. The sultan said: 'What is their sermon worth, when they still call to prayer with \"Come to the best of works\"? He must come before me and tread my carpet.' Mahmud refused, and the siege of the city was pressed hard; prices rose and the fighting grew fierce. One day the sultan advanced and came close to the city, and a stone from a mangonel struck his horse. When things became too heavy for Mahmud, he came out by night with his mother Mani'a, daughter of Waththab al-Numayri, and they went in to the sultan, and she said to him: 'This is my son; do with him as you like.' He received them kindly, gave Mahmud a robe of honour and restored him to his city; and Mahmud sent the sultan a great sum of money.",
     "note": "'Come to the best of works' is the Shi'i addition to the call to prayer: for the sultan a change of sermon without a change of practice is not submission. This is the siege Romanos' envoys found him at in the spring of 1071; Matthew of Edessa puts the failed siege of Edessa here too (Matt. Sultan [3])."},
]

BATTLE = [
    {"pg": "X, 44", "titel": "The king of the Rum marches",
     "orig": "ذكر خروج ملك الروم الى خلاط واسره\nفى هذه السنة خرج ارمانوس ملك الروم فى مائتين الوف من الروم والفرنج والغرب والروس والبجناك والكرج وغيرهم من طوايف تلك البلاد فجاوا فى تجمل كثير وزى عظيم وقصد بلاد الاسلام فوصل الى ملازكرد من اعمال خلاط،",
     "en": "How the king of the Rum went out to Khilat, and was taken.\nIn this year Armanus, king of the Rum, went out with two hundred thousands of Rum, Franks, Westerners, Rus, Pechenegs, Georgians and others of the peoples of those lands. They came in great array and splendid dress, and he made for the lands of Islam, and reached Malazkird, in the district of Khilat.",
     "note": "Armanus is Romanos. 'Two hundred thousands' as printed; one manuscript reads 'two hundred thousand'. The printed al-Gharb ('the Westerners') may hide al-Ghuzz, the Uzes, whom the Byzantine sources name; it is not emended here. The Pechenegs are missing in one manuscript. Malazkird is Manzikert; Khilat, Attaleiates' Khliat."},
    {"pg": "X, 44", "titel": "The sultan turns north",
     "orig": "فبلغ السلطان الب ارسلان الخبر وهو بمدينة خوى من اذربيجان قد عاد من حلب، وسمع ما هو ملك الروم فيه من كثرة الجموع فلم يتمكن من جمع العساكر لبعدها وقرب العدو، فسير الاثقال مع زوجته ونظام الملك الى همذان وسار هو فيمن عنده من العساكر وهم خمسة عشر الف فارس وجد فى السير وقال لهم اننى اقاتل محتسبا صابرا فان سلمت فنعمة من الله تعالى وان كانت الشهادة فان ابنى ملكشاه ولى عهدى، وساروا،",
     "en": "The news reached the sultan Alp Arslan at the town of Khuy in Azerbaijan, having come back from Aleppo. He heard of the great hosts the king of the Rum had with him, and he could not gather his armies, because they were far off and the enemy was near. So he sent the baggage with his wife and Nizam al-Mulk to Hamadhan, and marched himself with the troops he had, fifteen thousand horsemen, and pressed on. He said to them: 'I fight seeking my reward from God, and patient. If I come through, it is a grace from God most high; and if it is martyrdom, then my son Malikshah is my heir.' And they marched.",
     "note": "Nizam al-Mulk was the sultan's vizier, the great minister of the Seljuk state. The small army (fifteen thousand horse against two hundred thousand) is the chronicle's frame for a victory given by God; the Byzantine eyewitness also saw the sultan come up with only part of his forces (Att. Battle [11])."},
    {"pg": "X, 44", "titel": "The commander of the Rus loses his nose",
     "orig": "فلما قارب العدو جعل له مقدمة فصادفت مقدمته عند خلاط مقدم الروسية فى نحو عشرة الاف من الروم فاقتتلوا فانهزمت الروسية واسر مقدمهم وحمل الى السلطان فجدع انفه وانفذ بالسلب الى نظام الملك وامره ان يرسله الى بغداذ،",
     "en": "When he drew near the enemy he formed a vanguard, and his vanguard met, near Khilat, the commander of the Rus with about ten thousand of the Rum. They fought, and the Rus were routed; their commander was taken and brought to the sultan, who cut off his nose, and sent the spoils to Nizam al-Mulk with orders to send them on to Baghdad.",
     "note": "The 'Rus' (al-Rusiyya) may be the Varangians and other northern troops of the guard. A commander taken before the battle is in Attaleiates too (Basilakes, Att. Battle [3]). The cut nose answers, across the lines, the soldier whose nose the emperor cut off before the icon (Att. March [7])."},
    {"pg": "X, 44–45", "titel": "“No truce except at Rayy”",
     "orig": "فلما تقارب العسكران ارسل السلطان الى ملك الروم يطلب منه المهادنة فقال لا هدنة الا بالرى، فانزعج السلطان لذلك فقال له امامه وفقيهه ابو نصر محمد بن عبد الملك البخارى الحنفى انك تقاتل عن دين وعد الله بنصره واظهاره على ساير الاديان وارجو ان يكون الله تعالى قد كتب باسمك هذا الفتح فالقهم يوم الجمعة بعد الزوال فى الساعة التى تكون الخطباء على المنابر فانهم يدعون للمجاهدين بالنصر والدعاء مقرون بالاجابة،",
     "en": "When the two armies drew near each other, the sultan sent to the king of the Rum asking him for a truce. He said: 'No truce except at Rayy.' The sultan was troubled by this. His imam and jurist, Abu Nasr Muhammad ibn Abd al-Malik al-Bukhari the Hanafi, said to him: 'You fight for a religion to which God has promised His help and victory over all religions. I hope that God most high has written this conquest in your name. Meet them on Friday, after noon, at the hour when the preachers are in the pulpits; for they pray for victory for those who fight in God's way, and prayer is joined to its answer.'",
     "note": "Rayy, near modern Tehran, was a Seljuk capital: the emperor answers that he will make peace only in the sultan's own country. Attaleiates has the peace offer too, and its refusal on the advice of those who said the sultan was playing for time (Att. Battle [9], [11]). Friday 26 August 1071 is the date of the battle in the modern accounts."},
    {"pg": "X, 45", "titel": "The white shroud",
     "orig": "فلما كان تلك الساعة صلى بهم وبكى السلطان فبكى الناس لبكايه ودعا ودعوا معه وقال لهم من اراد الانصراف فلينصرف فما هاهنا سلطان يامر وينهى، والقى القوس والنشاب واخذ السيف والدبوس وعقد ذنب فرسه بيده وفعل عسكره مثله ولبس البياض وتحنط وقال ان قتلت فهذا كفنى،",
     "en": "When that hour came he prayed with them, and the sultan wept, and the people wept at his weeping; he prayed and they prayed with him. He said to them: 'Whoever wishes to leave, let him leave; there is no sultan here to command and forbid.' He threw down bow and arrows, took sword and mace, and knotted his horse's tail with his own hand, and his army did the same. He put on white and perfumed himself for burial, and said: 'If I am killed, this is my shroud.'",
     "note": "Setting aside the bow, the Turkish horseman's weapon, for sword and mace means close combat. The Byzantine eyewitness has the omens on his own side; here the preparation for death is the sultan's."},
    {"pg": "X, 45", "titel": "The battle",
     "orig": "وزحف الى الروم وزحفوا اليه فلما قاربهم ترجل وعفر وجهه على التراب وبكى واكثر الدعاء ثم ركب وحمل وحملت العساكر معه فحصل المسلمون فى وسطهم وحجز الغبار بينهم فقتل المسلمون فيهم كيف شاوا وانزل الله نصره عليهم فانهزم الروم وقتل منهم ما لا يحصى حتى امتلات الارض بجثث القتلى،",
     "en": "He advanced on the Rum and they advanced on him. When he came near them he dismounted, rubbed his face in the dust, wept and prayed much; then he mounted and charged, and the armies charged with him. The Muslims came into the middle of them, and the dust stood between them, and the Muslims killed among them as they pleased. God sent down His help upon them; the Rum were routed, and more of them were killed than can be counted, until the ground was full of the bodies of the dead.",
     "note": "One charge into the middle of the army, behind a wall of dust: nothing of the day's advance, the turned standard or the flight of the rear that Attaleiates describes (Att. Battle [11]–[13])."},
    {"pg": "X, 45", "titel": "Taken by a slave no one wanted",
     "orig": "واسر ملك الروم اسره بعض غلمان كوهرائين اراد قتله ولم يعرفه فقال له خادم مع الملك لا تقتله فانه الملك، وكان هذا الغلام قد عرضه كوهرائين على نظام الملك فرده استحقارا له فاثنى عليه كوهرائين فقال نظام الملك عسى ان ياتينا بملك الروم اسيرا فكان كذلك،",
     "en": "The king of the Rum was taken. One of the slave soldiers of Gawhara'in took him; he meant to kill him, not knowing who he was, but a eunuch who was with the king said to him: 'Do not kill him, for he is the king.' This slave had once been presented by Gawhara'in to Nizam al-Mulk, who turned him down in contempt; Gawhara'in praised him, and Nizam al-Mulk said: 'Perhaps he will bring us the king of the Rum as a captive.' And so it was.",
     "note": "Gawhara'in was a Turkish commander of the sultan's household. The anecdote of the despised slave turns the capture into a lesson on the vizier's words."},
    {"pg": "X, 45", "titel": "“What would you have done?”",
     "orig": "فلما اسر الغلام الملك احضره عند كوهرائين فقصد السلطان واخبره باسر الملك فامر باحضاره، فلما احضر ضربه السلطان الب ارسلان ثلاث مقارع بيده وقال له الم ارسل اليك فى الهدنة فابيت، فقال دعنى من التوبيخ وافعل ما تريد، فقال السلطان ما عزمت ان تفعل بى ان اسرتنى، فقال افعل القبيح، قال له فما تظن اننى افعل بك، قال اما ان تقتلنى واما ان تشهرنى فى بلاد الاسلام والاخرى بعيدة وهى العفو وقبول الاموال واصطناعى نايبا عنك، قال ما عزمت على غير هذا،",
     "en": "When the slave had taken the king, he brought him before Gawhara'in, who went to the sultan and told him of the king's capture, and he ordered him brought. When he was brought, the sultan Alp Arslan struck him three blows with his own hand and said to him: 'Did I not send to you for a truce, and you refused?' He said: 'Spare me the reproaches and do what you will.' The sultan said: 'What had you resolved to do with me, if you had taken me?' He said: 'Something ugly.' He said: 'Then what do you think I shall do with you?' He said: 'Either you will kill me, or you will parade me through the lands of Islam; the third is unlikely, and that is pardon, the taking of money, and making me your deputy.' He said: 'I have resolved on nothing but this.'",
     "note": "The same exchange as in Attaleiates (Att. Capt. [4]) with the roles weighted differently: blows first, then the pardon; the emperor's 'something ugly' for his 'I would have used up your body with blows'. Attaleiates has the sultan rise and embrace him (Att. Capt. [2]). 'Deputy' (na'ib) makes the emperor the sultan's vassal."},
    {"pg": "X, 45–46", "titel": "The ransom and the fifty years' truce",
     "orig": "ففداه بالف الف دينار وخمس ماية الف دينار وان يرسل اليه عساكر الروم اى وقت طلبها وان يطلق كل اسير فى بلاد الروم، واستقر الامر على ذلك وانزله فى خيمة وارسل اليه عشرة الاف دينار يتجهز بها واطلق له جماعة من البطارقة وخلع عليه من الغد، فقال ملك الروم اين جهة الخليفة فدل عليها فقام وكشف راسه واوما الى الارض بالخدمة، وهادنه السلطان خمسين سنة وسيره الى بلاده وسير معه عسكرا اوصلوه الى مامنه وشيعه السلطان فرسخا،",
     "en": "He ransomed him for a thousand thousand dinars and five hundred thousand dinars, on condition that he send him the armies of the Rum whenever he asked for them, and release every captive in the lands of the Rum. The matter was settled on this. He lodged him in a tent and sent him ten thousand dinars to equip himself with, released a number of his patricians to him, and the next day gave him a robe of honour. The king of the Rum said: 'Where is the direction of the caliph?' It was pointed out to him; he stood, uncovered his head, and bowed to the ground in homage. The sultan made a truce with him for fifty years and sent him to his country, sending troops with him who brought him to a place of safety; and the sultan escorted him a parasang.",
     "note": "One and a half million dinars, troops on demand and the release of captives: the terms Attaleiates reduces to 'only a generous gift' (Att. Capt. [5]). The emperor's bow towards Baghdad makes the victory the caliph's; one manuscript lacks 'the next day'."},
    {"pg": "X, 46", "titel": "Michael seizes the kingdom",
     "orig": "واما الروم فلما بلغهم خبر الوقعة وثب ميخائيل على المملكة فملك البلاد، فلما وصل ارمانوس الملك الى قلعة دوقية بلغه الخبر فلبس الصوف واظهر الزهد وارسل الى ميخائيل يعرفه ما تقرر مع السلطان وقال ان شئت ان تفعل ما استقر وان شئت امسكت، فاجابه ميخائيل بايثار ما استقر وطلب وساطته وسوال السلطان فى ذلك، وجمع ارمانوس ما عنده من المال فكان مايتى الف دينار فارسله الى السلطان وطبق ذهب عليه جواهر بتسعين الف دينار وحلف له انه لا يقدر على غير ذلك، ثم ان ارمانوس استولى على اعمال الارمن وبلادهم، ومدح الشعراء السلطان وذكروا هذا الفتح فاكثروا.",
     "en": "As for the Rum: when the news of the battle reached them, Mikha'il leapt upon the kingdom and took possession of the country. When the king Armanus reached the fortress of Duqiya, the news reached him. He put on wool and made a show of renunciation, and sent to Mikha'il to tell him what had been agreed with the sultan, saying: 'If you wish, carry out what was settled; and if you wish, I will hold back.' Mikha'il answered that he preferred what had been settled, and asked for his mediation and for a request to the sultan about it. Armanus gathered the money he had, and it was two hundred thousand dinars; he sent it to the sultan, with a gold tray set with jewels worth ninety thousand dinars, and swore to him that he could do no more. Then Armanus took possession of the districts of the Armenians and their country. The poets praised the sultan and celebrated this conquest, and did so abundantly.",
     "note": "Duqiya is Dokeia, where the Doukai first beat Romanos in the civil war. The wool is the monk's habit; in the Byzantine and Armenian accounts Romanos takes it only at Adana, as the price of his life. Of the blinding Ibn al-Athir says nothing here. 'Took possession of the districts of the Armenians' may mean Romanos' retreat into Cilicia and the Armenian lords' country in 1072. The chapter ends with the poets."},
]

SECTIONS = [
    {"id": "aleppo", "zk": "IA Aleppo", "titel": "The year 463: Aleppo",
     "blurb": "The sultan's war in 1070–71 was for the Abbasid caliph against Fatimid Egypt: Aleppo changes its Friday sermon to Baghdad, the sultan wants more than a sermon, and besieges the city until its lord and his mother come out to him by night. This is where Romanos' envoys found him.",
     "units": ALEPPO},
    {"id": "battle", "zk": "IA Battle", "titel": "The king of the Rum at Malazkird",
     "blurb": "The Seljuk side of the battle, written in Mosul a century and a half later: fifteen thousand horse against two hundred thousand, the peace refused ('no truce except at Rayy'), the Friday prayer and the white shroud, one charge through the dust, a despised slave who takes the emperor, three blows and the question, the ransom and the fifty years' truce, and the Doukas coup seen from the sultan's court.",
     "units": BATTLE},
]
